In [1]:
import pandas as pd
pd.__version__

'3.0.5'

In [2]:
from scipy.stats import norm

In [3]:
norm.cdf(0)

np.float64(0.5)

In [4]:
S = 100 
K = 100
r = 0.05
sigma = 0.2
T = 1

In [5]:
import numpy as np

In [6]:
d1 = (np.log(S/K) + (r + sigma**2 / 2)) * T / (sigma * np.sqrt(T))
d2 = d1 - sigma * np.sqrt(T)

d1, d2

(np.float64(0.35000000000000003), np.float64(0.15000000000000002))

In [7]:
N_d1 = norm.cdf(d1)
N_d2 = norm.cdf(d2)

N_d1, N_d2

(np.float64(0.6368306511756191), np.float64(0.5596176923702425))

In [8]:
call_price = S * N_d1 - K * np.exp(-r * T) * N_d2
call_price

np.float64(10.450583572185565)

In [9]:
import sys
sys.path.append('../src')

In [10]:
from black_scholes import black_scholes_call

In [11]:
black_scholes_call(S = 100, K = 100 , sigma = 0.2, r = 0.05, T = 1)

np.float64(10.450583572185565)

In [12]:
import sys
sys.path.append('../src')
from black_scholes import black_scholes_put

In [13]:
from black_scholes import black_scholes_put
black_scholes_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(5.573526022256971)

In [14]:
import importlib
import black_scholes
importlib.reload(black_scholes)
from black_scholes import black_scholes_call, black_scholes_put

In [15]:
from black_scholes import delta_call
from black_scholes import delta_put

In [16]:
delta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(0.6368306511756191)

In [17]:
delta_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-0.3631693488243809)

In [18]:

import importlib
importlib.reload(black_scholes)

In [19]:
from black_scholes import gamma

In [20]:
gamma(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(0.018762017345846895)

In [21]:
import importlib
importlib.reload(black_scholes)
from black_scholes import vega

In [22]:
vega(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(37.52403469169379)

In [23]:
vega(S=100, K=150, r=0.05, sigma=0.2, T=1)

np.float64(9.772000145726361)

In [24]:
import importlib
importlib.reload(black_scholes)

In [25]:
from black_scholes import theta_call
theta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-6.414027546438197)

In [26]:
import importlib
importlib.reload(black_scholes)

In [27]:
from black_scholes import rho_call
rho_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(53.232481545376345)

In [28]:
from black_scholes import rho_put
rho_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-41.89046090469506)

In [29]:
import importlib

In [30]:
importlib.reload(black_scholes)

In [31]:
from black_scholes import delta_call_numerical, delta_call

In [32]:
numerical = delta_call_numerical(S=100, K=100, r=0.05, sigma=0.2, T=1)
analytical = delta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

numerical, analytical

(np.float64(0.6368306425763137), np.float64(0.6368306511756191))

In [33]:
import importlib
importlib.reload(black_scholes)

In [34]:
from black_scholes import gamma_numerical
gamma_numerical(S=100, K=100, r=0.05, sigma=0.2, T=1, h=0.0001)

np.float64(0.018761880937745445)

In [35]:
import sys, os
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))

In [36]:
from binomial import binomial_price
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=3, q=0)

np.float64(11.043871091951113)

In [37]:
from binomial import binomial_price
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=2, q=0, option_type='call', american=False)

np.float64(9.540501338582947)

In [38]:
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=100, q=0, option_type='call', american=False)

np.float64(10.430611662249113)

In [39]:
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='call', american=False)

np.float64(10.44658513644654)

In [40]:
import importlib
importlib.reload(black_scholes)

In [41]:
# American put, deep in-the-money — early exercise should add real value here
binomial_price(S=80, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='put', american=True)

np.float64(20.0)

In [42]:
binomial_price(S=80, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='put', american=False)

np.float64(16.983137118259393)

In [43]:
from monte_carlo import monte_carlo_call
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=5, seed=42)

np.float64(13.522454507401847)

In [44]:
from monte_carlo import monte_carlo_call
# restart kernel first

monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=5, seed=42)

np.float64(13.522454507401847)

In [45]:
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=100000, seed=42)

np.float64(10.47389196070258)

In [46]:
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=1000000, seed=42)

np.float64(10.434157688982824)

In [47]:
# Run 100,000 sims five separate times (no fixed seed) — watch how much they vary
[monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=1000000) for _ in range(5)]

[np.float64(10.459202124096821),
 np.float64(10.452150509799127),
 np.float64(10.450558888427537),
 np.float64(10.456686428080205),
 np.float64(10.438973533748085)]

In [48]:
from monte_carlo import monte_carlo_call, monte_carlo_call_antithetic
# restart kernel first

[monte_carlo_call_antithetic(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=1000000, seed=42) for _ in range(5)]

[np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086)]

In [49]:
# Plain Monte Carlo — 5 runs, small n_simulations to make spread visible
[monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000) for _ in range(5)]

[np.float64(10.367033313398208),
 np.float64(10.610462259003915),
 np.float64(10.309140256582728),
 np.float64(10.380410291111975),
 np.float64(10.55075981829986)]

In [50]:
# Antithetic — same n_simulations, 5 runs
[monte_carlo_call_antithetic(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000) for _ in range(5)]

[np.float64(10.6240416300026),
 np.float64(10.546187221169946),
 np.float64(10.450979180137036),
 np.float64(10.479650982262912),
 np.float64(10.480538365483373)]

In [51]:
from monte_carlo import monte_carlo_call_control_variate
[monte_carlo_call_control_variate(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000)for _ in range(5)]

[np.float64(10.451839876232127),
 np.float64(10.45647104530929),
 np.float64(10.448927776987459),
 np.float64(10.454923225108473),
 np.float64(10.417638670537002)]

In [52]:
import yfinance as yf
reliance = yf.Ticker("RELIANCE.NS")
reliance.info

{'address1': 'Maker Chambers IV',
 'address2': '3rd Floor 222 Nariman Point',
 'city': 'Mumbai',
 'zip': '400021',
 'country': 'India',
 'phone': '91 22 3555 5000',
 'fax': '91 22 2204 2268',
 'website': 'https://www.ril.com',
 'industry': 'Oil & Gas Refining & Marketing',
 'industryKey': 'oil-gas-refining-marketing',
 'industryDisp': 'Oil & Gas Refining & Marketing',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Reliance Industries Limited engages in hydrocarbon exploration and production, petroleum refining and marketing, petrochemicals, advanced materials and composites, renewable, financial services, retail, and digital services worldwide. It operates through the Oil to Chemicals, Oil and Gas, Retail, Digital Services, and Others segments. The company is involved in refining and marketing products, including liquefied petroleum gas, propylene, naphtha, gasoline, jet/aviation turbine fuel, kerosine oil, diesel, sulfur, and petroleum coke. It also provides polymers comprising high-density and low-density polyethylene (PE), linear low-density PE, homopolymer, random and impact copolymer, and polyvinyl chloride; fiber intermediates that include purified terephthalic acid, and ethylene glycols and oxide; aromatics, such as paraxylene, ortho xylene, benzene, and linear alkyl benzene and paraffin; and textiles that consist of fabrics, apparel, and auto furnishings. In addition, the company offers elastomers, such as polybutadiene rubber, styrene butadiene rubber, and butyl rubber; fiber and yarn polyesters; and bioenergy solutions, including compressed biogas, and pellets and briquettes. Further, it engages in oil and gas exploration and production activities; operation of various stores comprising supermarkets, hypermarket, wholesale cash and carry, specialty, and online stores; operation of media and entertainment platforms, and Network18 and television channels; and publishing of magazines. Additionally, the company provides highway hospitality and fleet management services, as well as digital services, such as connectivity, fiber, mobile devices, apps, business, and other digital solutions. Reliance Industries Limited was founded in 1957 and is based in Mumbai, India.',
 'fullTimeEmployees': 404501,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Mukesh Dhirubhai Ambani',
   'age': 68,
   'title': 'Chairman & MD',
   'yearBorn': 1957,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nikhil Rasiklal Meswani',
   'age': 59,
   'title': 'Executive Director',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hital Rasiklal Meswani',
   'age': 57,
   'title': 'Executive Director',
   'yearBorn': 1968,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Panda Madhusudana Siva Prasad',
   'age': 73,
   'title': 'Executive Director',
   'yearBorn': 1952,
   'fiscalYear': 2026,
   'totalPay': 205800000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anant Mukesh Ambani',
   'age': 30,
   'title': 'Whole-Time Director',
   'yearBorn': 1995,
   'fiscalYear': 2026,
   'totalPay': 123900000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Parul  Sharma',
   'title': 'Group President',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Srikanth  Venkatachari',
   'age': 59,
   'title': 'Chief Financial Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mahesh  Marve',
   'title': 'Head of Research & Technology',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hemen Kanu Modi',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Savithri  Parekh',
   'age': 59,
   'title': 'Company Secretary & Compliance Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 9,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 10,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1798675200,
 'irWebsite': 'http://ril.com/html/investor/investor.html',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1287.0,
 'open': 1278.7,
 'dayLow': 1271.0,
 'dayHigh': 1279.7,
 'regularMarketPreviousClose': 1287.0,
 'regularMarketOpen': 1278.7,
 'regularMarketDayLow': 1271.0,
 'regularMarketDayHigh': 1279.7,
 'dividendRate': 6.0,
 'dividendYield': 0.47,
 'exDividendDate': 1780617600,
 'payoutRatio': 0.2083,
 'fiveYearAvgDividendYield': 0.44,
 'beta': 0.157,
 'trailingPE': 23.140736,
 'forwardPE': 17.877417,
 'volume': 3099798,
 'regularMarketVolume': 3099785,
 'averageVolume': 12831951,
 'averageVolume10days': 8027361,
 'averageDailyVolume10Day': 8027361,
 'bid': 1277.8,
 'ask': 1277.8,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 17289086763008,
 'nonDilutedMarketCap': 17351336411314,
 'fiftyTwoWeekLow': 1249.8,
 'fiftyTwoWeekHigh': 1611.8,
 'allTimeHigh': 1611.8,
 'allTimeLow': 5.428648,
 'fulldayPrice': 1277.6,
 'priceToSalesTrailing12Months': 1.5304228,
 'fiftyDayAverage': 1304.352,
 'twoHundredDayAverage': 1388.9225,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'INR',
 'tradeable': False,
 'enterpriseValue': 20633182273536,
 'profitMargins': 0.066149995,
 'floatShares': 6638895750,
 'sharesOutstanding': 13532472634,
 'heldPercentInsiders': 0.51798,
 'heldPercentInstitutions': 0.28070998,
 'impliedSharesOutstanding': 13532472635,
 'bookValue': 668.045,
 'priceToBook': 1.912446,
 'lastFiscalYearEnd': 1774915200,
 'nextFiscalYearEnd': 1806451200,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': -0.224,
 'netIncomeToCommon': 747269980160,
 'trailingEps': 55.21,
 'forwardEps': 71.46446,
 'pegRatio': 0.82,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1730073600,
 'enterpriseToRevenue': 1.827,
 'enterpriseToEbitda': 11.423,
 '52WeekChange': -0.049412787,
 'SandP52WeekChange': 0.20204377,
 'lastDividendValue': 6.0,
 'lastDividendDate': 1780617600,
 'quoteType': 'EQUITY',
 'currentPrice': 1277.5,
 'targetHighPrice': 1890.0,
 'targetLowPrice': 1350.0,
 'targetMeanPrice': 1677.8889,
 'targetMedianPrice': 1690.0,
 'recommendationMean': 1.30769,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 27,
 'totalCash': 2581470117888,
 'totalCashPerShare': 190.761,
 'ebitda': 1806359986176,
 'totalDebt': 3979999969280,
 'totalRevenue': 11296050249728,
 'debtToEquity': 36.653,
 'revenuePerShare': 834.734,
 'grossProfits': 3822279983104,
 'earningsGrowth': -0.224,
 'revenueGrowth': 0.297,
 'grossMargins': 0.33837003,
 'ebitdaMargins': 0.15991001,
 'operatingMargins': 0.12331,
 'financialCurrency': 'INR',
 'symbol': 'RELIANCE.NS',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Free Realtime Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'regularMarketTime': 1788155139,
 'exchange': 'NSI',
 'messageBoardId': 'finmb_878373',
 'exchangeTimezoneName': 'Asia/Kolkata',
 'exchangeTimezoneShortName': 'IST',
 'gmtOffSetMilliseconds': 19800000,
 'market': 'in_market',
 'esgPopulated': False,
 'marketState': 'REGULAR',
 'regularMarketChange': -9.400024,
 'fulldayChange': -9.400024,
 'fulldayChangePercent': -0.7303826,
 'regularMarketDayRange': '1271.0 - 1279.7',
 'fullExchangeName': 'NSE',
 'averageDailyVolume3Month': 12831951,
 'fiftyTwoWeekLowChange': 27.799927,
 'fiftyTwoWeekLowChangePercent': 0.0222435,
 'fiftyTwoWeekRange': '1249.8 - 1611.8',
 'fiftyTwoWeekHighChange': -334.20007,
 'fiftyTwoWeekHighChangePercent': -0.20734586,
 'fiftyTwoWeekChangePercent': -4.9412785,
 'earningsTimestamp': 1784282400,
 'earningsTimestampStart': 1792144800,
 'earningsTimestampEnd': 1792144800,
 'earningsCallTimestampStart': 1745592300,
 'earningsCallTimestampEnd': 1745592300,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 55.21,
 'epsForward': 71.46446,
 'epsCurrentYear': 64.0101,
 'regularMarketChangePercent': -0.7303826,
 'regularMarketPrice': 1277.6,
 'priceEpsCurrentYear': 19.959349,
 'fiftyDayAverageChange': -26.752075,
 'fiftyDayAverageChangePercent': -0.020509858,
 'twoHundredDayAverageChange': -111.32251,
 'twoHundredDayAverageChangePercent': -0.08015027,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 820467900000,
 'shortName': 'RELIANCE INDUSTRIES LTD',
 'longName': 'Reliance Industries Limited',
 'trailingPegRatio': None}

In [53]:
reliance = yf.Ticker("RELIANCE.NS")
price = reliance.info['currentPrice']
price

1277.9

In [54]:
history = reliance.history(period="1d")
history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-31 00:00:00+05:30,1278.699951,1279.699951,1271.0,1277.5,3099798,0.0,0.0

In [55]:
latest_price = history['Close'].iloc[-1]
latest_price

np.float64(1277.5)

In [56]:
history = reliance.history(period = "1d")
latest_price = history['Close'].iloc[-1]
latest_price

np.float64(1277.5)

In [57]:
from market_data import get_spot_price
get_spot_price("RELIANCE.NS")

1277.5

In [58]:
get_spot_price("SILVERBEES.NS")

222.52999877929688

In [59]:
get_spot_price("AAPL")

319.70001220703125

In [60]:
reliance = yf.Ticker("RELIANCE.NS")
expiries = reliance.options
expiries

()

In [61]:
nifty = yf.Ticker("^NSEI")
nifty.options

()

In [62]:
tcs = yf.Ticker("TCS.NS")
tcs.options

()

In [63]:
aapl = yf.Ticker("AAPL")
expiries = aapl.options
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-09',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-09',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [64]:
chain = aapl.option_chain(expiries[0])
chain.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:43+00:00,225.0,95.54,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
1,AAPL260831C00230000,2026-08-28 14:21:14+00:00,230.0,86.63,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
2,AAPL260831C00235000,2026-08-17 18:05:20+00:00,235.0,68.01,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
3,AAPL260831C00240000,2026-08-17 18:05:20+00:00,240.0,63.00,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
4,AAPL260831C00250000,2026-08-20 14:33:30+00:00,250.0,66.80,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
5,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,0.0,0.0,0.0,0.0,1.0,0.0,0.000010,True,REGULAR,USD
6,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
7,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,0.0,0.0,0.0,0.0,7.0,0.0,0.000010,True,REGULAR,USD
8,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,0.0,0.0,0.0,0.0,7.0,0.0,0.000010,True,REGULAR,USD
9,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,0.0,0.0,0.0,0.0,4.0,0.0,0.000010,True,REGULAR,USD
10,AAPL260831C00290000,2026-08-28 14:14:28+00:00,290.0,26.38,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
11,AAPL260831C00292500,2026-08-25 19:52:33+00:00,292.5,17.15,0.0,0.0,0.0,0.0,213.0,0.0,0.000010,True,REGULAR,USD
12,AAPL260831C00295000,2026-08-28 19:47:08+00:00,295.0,25.07,0.0,0.0,0.0,0.0,110.0,0.0,0.000010,True,REGULAR,USD
13,AAPL260831C00297500,2026-08-28 16:02:06+00:00,297.5,23.78,0.0,0.0,0.0,0.0,10.0,0.0,0.000010,True,REGULAR,USD
14,AAPL260831C00300000,2026-08-28 18:14:24+00:00,300.0,19.84,0.0,0.0,0.0,0.0,6.0,0.0,0.000010,True,REGULAR,USD
15,AAPL260831C00302500,2026-08-28 13:46:02+00:00,302.5,13.65,0.0,0.0,0.0,0.0,4.0,0.0,0.000010,True,REGULAR,USD
16,AAPL260831C00305000,2026-08-28 19:35:13+00:00,305.0,15.08,0.0,0.0,0.0,0.0,10.0,0.0,0.000010,True,REGULAR,USD
17,AAPL260831C00307500,2026-08-28 19:59:51+00:00,307.5,10.95,0.0,0.0,0.0,0.0,71.0,0.0,0.000010,True,REGULAR,USD
18,AAPL260831C00310000,2026-08-28 19:53:16+00:00,310.0,10.00,0.0,0.0,0.0,0.0,481.0,0.0,0.000010,True,REGULAR,USD
19,AAPL260831C00312500,2026-08-28 19:57:34+00:00,312.5,7.65,0.0,0.0,0.0,0.0,567.0,0.0,0.000010,True,REGULAR,USD
20,AAPL260831C00315000,2026-08-28 19:58:41+00:00,315.0,5.25,0.0,0.0,0.0,0.0,6777.0,0.0,0.000010,True,REGULAR,USD
21,AAPL260831C00317500,2026-08-28 19:59:32+00:00,317.5,3.05,0.0,0.0,0.0,0.0,14265.0,0.0,0.000010,True,REGULAR,USD
22,AAPL260831C00320000,2026-08-28 19:59:58+00:00,320.0,1.40,0.0,0.0,0.0,0.0,32256.0,0.0,0.007822,False,REGULAR,USD
23,AAPL260831C00322500,2026-08-28 19:59:55+00:00,322.5,0.69,0.0,0.0,0.0,0.0,25298.0,0.0,0.031260,False,REGULAR,USD
24,AAPL260831C00325000,2026-08-28 19:59:58+00:00,325.0,0.27,0.0,0.0,0.0,0.0,21611.0,0.0,0.062509,False,REGULAR,USD
25,AAPL260831C00327500,2026-08-28 19:59:54+00:00,327.5,0.13,0.0,0.0,0.0,0.0,5805.0,0.0,0.125009,False,REGULAR,USD
26,AAPL260831C00330000,2026-08-28 19:59:40+00:00,330.0,0.08,0.0,0.0,0.0,0.0,7447.0,0.0,0.125009,False,REGULAR,USD
27,AAPL260831C00332500,2026-08-28 19:59:27+00:00,332.5,0.05,0.0,0.0,0.0,0.0,833.0,0.0,0.125009,False,REGULAR,USD
28,AAPL260831C00335000,2026-08-28 19:59:05+00:00,335.0,0.03,0.0,0.0,0.0,0.0,479.0,0.0,0.250007,False,REGULAR,USD
29,AAPL260831C00337500,2026-08-28 19:31:25+00:00,337.5,0.02,0.0,0.0,0.0,0.0,856.0,0.0,0.250007,False,REGULAR,USD
30,AAPL260831C00340000,2026-08-28 19:40:08+00:00,340.0,0.03,0.0,0.0,0.0,0.0,88.0,0.0,0.250007,False,REGULAR,USD
31,AAPL260831C00342500,2026-08-28 17:31:44+00:00,342.5,0.01,0.0,0.0,0.0,0.0,8.0,0.0,0.250007,False,REGULAR,USD
32,AAPL260831C00345000,2026-08-28 16:34:49+00:00,345.0,0.03,0.0,0.0,0.0,0.0,74.0,0.0,0.250007,False,REGULAR,USD
33,AAPL260831C00347500,2026-08-28 16:27:58+00:00,347.5,0.02,NaN,0.0,0.0,0.0,NaN,0.0,0.250007,False,REGULAR,USD
34,AAPL260831C00350000,2026-08-28 18:09:22+00:00,350.0,0.01,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
35,AAPL260831C00355000,2026-08-26 19:14:51+00:00,355.0,0.01,0.0,0.0,0.0,0.0,76.0,0.0,0.500005,False,REGULAR,USD
36,AAPL260831C00360000,2026-08-27 16:41:21+00:00,360.0,0.01,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
37,AAPL260831C00365000,2026-08-21 18:59:47+00:00,365.0,0.07,0.0,0.0,0.0,0.0,6.0,0.0,0.500005,False,REGULAR,USD
38,AAPL260831C00370000,2026-08-21 19:00:54+00:00,370.0,0.07,0.0,0.0,0.0,0.0,26.0,0.0,0.500005,False,REGULAR,USD
39,AAPL260831C00375000,2026-08-25 14:43:57+00:00,375.0,0.02,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
40,AAPL260831C00380000,2026-08-28 14:45:09+00:00,380.0,0.01,0.0,0.0,0.0,0.0,3.0,0.0,0.500005,False,REGULAR,USD
41,AAPL260831C00385000,2026-08-28 15:58:14+00:00,385.0,0.01,0.0,0.0,0.0,0.0,1.0,0.0,0.500005,False,REGULAR,USD
42,AAPL260831C00390000,2026-08-26 16:34:00+00:00,390.0,0.01,NaN,0.0,0.0,0.0,NaN,0.0,0.500005,False,REGULAR,USD
43,AAPL260831C00405000,2026-08-28 13:30:10+00:00,405.0,0.01,NaN,0.0,0.0,0.0,NaN,NaN,0.500005,False,REGULAR,USD

In [65]:
from market_data import get_spot_price
get_spot_price("AAPL")

319.70001220703125

In [66]:
chain.calls.shape

(44, 14)

In [67]:
chain.calls.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='str')

In [68]:
chain.calls.head(10)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:43+00:00,225.0,95.54,0.0,0.0,0.0,0.0,2.0,0.0,0.00001,True,REGULAR,USD
1,AAPL260831C00230000,2026-08-28 14:21:14+00:00,230.0,86.63,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
2,AAPL260831C00235000,2026-08-17 18:05:20+00:00,235.0,68.01,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
3,AAPL260831C00240000,2026-08-17 18:05:20+00:00,240.0,63.00,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
4,AAPL260831C00250000,2026-08-20 14:33:30+00:00,250.0,66.80,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
5,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,0.0,0.0,0.0,0.0,1.0,0.0,0.00001,True,REGULAR,USD
6,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,0.0,0.0,0.0,0.0,2.0,0.0,0.00001,True,REGULAR,USD
7,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,0.0,0.0,0.0,0.0,7.0,0.0,0.00001,True,REGULAR,USD
8,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,0.0,0.0,0.0,0.0,7.0,0.0,0.00001,True,REGULAR,USD
9,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,0.0,0.0,0.0,0.0,4.0,0.0,0.00001,True,REGULAR,USD

In [69]:
import importlib
import market_data

importlib.reload(market_data)

In [70]:
from market_data import filter_liquid_options

liquid_calls = filter_liquid_options(chain.calls)
liquid_calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:43+00:00,225.0,95.54,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
5,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,0.0,0.0,0.0,0.0,1.0,0.0,0.000010,True,REGULAR,USD
6,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
7,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,0.0,0.0,0.0,0.0,7.0,0.0,0.000010,True,REGULAR,USD
8,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,0.0,0.0,0.0,0.0,7.0,0.0,0.000010,True,REGULAR,USD
9,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,0.0,0.0,0.0,0.0,4.0,0.0,0.000010,True,REGULAR,USD
10,AAPL260831C00290000,2026-08-28 14:14:28+00:00,290.0,26.38,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
11,AAPL260831C00292500,2026-08-25 19:52:33+00:00,292.5,17.15,0.0,0.0,0.0,0.0,213.0,0.0,0.000010,True,REGULAR,USD
12,AAPL260831C00295000,2026-08-28 19:47:08+00:00,295.0,25.07,0.0,0.0,0.0,0.0,110.0,0.0,0.000010,True,REGULAR,USD
13,AAPL260831C00297500,2026-08-28 16:02:06+00:00,297.5,23.78,0.0,0.0,0.0,0.0,10.0,0.0,0.000010,True,REGULAR,USD
14,AAPL260831C00300000,2026-08-28 18:14:24+00:00,300.0,19.84,0.0,0.0,0.0,0.0,6.0,0.0,0.000010,True,REGULAR,USD
15,AAPL260831C00302500,2026-08-28 13:46:02+00:00,302.5,13.65,0.0,0.0,0.0,0.0,4.0,0.0,0.000010,True,REGULAR,USD
16,AAPL260831C00305000,2026-08-28 19:35:13+00:00,305.0,15.08,0.0,0.0,0.0,0.0,10.0,0.0,0.000010,True,REGULAR,USD
17,AAPL260831C00307500,2026-08-28 19:59:51+00:00,307.5,10.95,0.0,0.0,0.0,0.0,71.0,0.0,0.000010,True,REGULAR,USD
18,AAPL260831C00310000,2026-08-28 19:53:16+00:00,310.0,10.00,0.0,0.0,0.0,0.0,481.0,0.0,0.000010,True,REGULAR,USD
19,AAPL260831C00312500,2026-08-28 19:57:34+00:00,312.5,7.65,0.0,0.0,0.0,0.0,567.0,0.0,0.000010,True,REGULAR,USD
20,AAPL260831C00315000,2026-08-28 19:58:41+00:00,315.0,5.25,0.0,0.0,0.0,0.0,6777.0,0.0,0.000010,True,REGULAR,USD
21,AAPL260831C00317500,2026-08-28 19:59:32+00:00,317.5,3.05,0.0,0.0,0.0,0.0,14265.0,0.0,0.000010,True,REGULAR,USD
22,AAPL260831C00320000,2026-08-28 19:59:58+00:00,320.0,1.40,0.0,0.0,0.0,0.0,32256.0,0.0,0.007822,False,REGULAR,USD
23,AAPL260831C00322500,2026-08-28 19:59:55+00:00,322.5,0.69,0.0,0.0,0.0,0.0,25298.0,0.0,0.031260,False,REGULAR,USD
24,AAPL260831C00325000,2026-08-28 19:59:58+00:00,325.0,0.27,0.0,0.0,0.0,0.0,21611.0,0.0,0.062509,False,REGULAR,USD
25,AAPL260831C00327500,2026-08-28 19:59:54+00:00,327.5,0.13,0.0,0.0,0.0,0.0,5805.0,0.0,0.125009,False,REGULAR,USD
26,AAPL260831C00330000,2026-08-28 19:59:40+00:00,330.0,0.08,0.0,0.0,0.0,0.0,7447.0,0.0,0.125009,False,REGULAR,USD
27,AAPL260831C00332500,2026-08-28 19:59:27+00:00,332.5,0.05,0.0,0.0,0.0,0.0,833.0,0.0,0.125009,False,REGULAR,USD
28,AAPL260831C00335000,2026-08-28 19:59:05+00:00,335.0,0.03,0.0,0.0,0.0,0.0,479.0,0.0,0.250007,False,REGULAR,USD
29,AAPL260831C00337500,2026-08-28 19:31:25+00:00,337.5,0.02,0.0,0.0,0.0,0.0,856.0,0.0,0.250007,False,REGULAR,USD
30,AAPL260831C00340000,2026-08-28 19:40:08+00:00,340.0,0.03,0.0,0.0,0.0,0.0,88.0,0.0,0.250007,False,REGULAR,USD
31,AAPL260831C00342500,2026-08-28 17:31:44+00:00,342.5,0.01,0.0,0.0,0.0,0.0,8.0,0.0,0.250007,False,REGULAR,USD
32,AAPL260831C00345000,2026-08-28 16:34:49+00:00,345.0,0.03,0.0,0.0,0.0,0.0,74.0,0.0,0.250007,False,REGULAR,USD
34,AAPL260831C00350000,2026-08-28 18:09:22+00:00,350.0,0.01,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
35,AAPL260831C00355000,2026-08-26 19:14:51+00:00,355.0,0.01,0.0,0.0,0.0,0.0,76.0,0.0,0.500005,False,REGULAR,USD
36,AAPL260831C00360000,2026-08-27 16:41:21+00:00,360.0,0.01,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
37,AAPL260831C00365000,2026-08-21 18:59:47+00:00,365.0,0.07,0.0,0.0,0.0,0.0,6.0,0.0,0.500005,False,REGULAR,USD
38,AAPL260831C00370000,2026-08-21 19:00:54+00:00,370.0,0.07,0.0,0.0,0.0,0.0,26.0,0.0,0.500005,False,REGULAR,USD
39,AAPL260831C00375000,2026-08-25 14:43:57+00:00,375.0,0.02,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
40,AAPL260831C00380000,2026-08-28 14:45:09+00:00,380.0,0.01,0.0,0.0,0.0,0.0,3.0,0.0,0.500005,False,REGULAR,USD
41,AAPL260831C00385000,2026-08-28 15:58:14+00:00,385.0,0.01,0.0,0.0,0.0,0.0,1.0,0.0,0.500005,False,REGULAR,USD

In [71]:
liquid_calls.shape

(37, 14)

In [72]:
liquid_calls[['strike', 'volume', 'openInterest', 'impliedVolatility', 'bid', 'ask']].head(10)

    strike  volume  openInterest  impliedVolatility  bid  ask
0    225.0     2.0           0.0            0.00001  0.0  0.0
5    275.0     1.0           0.0            0.00001  0.0  0.0
6    280.0     2.0           0.0            0.00001  0.0  0.0
7    282.5     7.0           0.0            0.00001  0.0  0.0
8    285.0     7.0           0.0            0.00001  0.0  0.0
9    287.5     4.0           0.0            0.00001  0.0  0.0
10   290.0     2.0           0.0            0.00001  0.0  0.0
11   292.5   213.0           0.0            0.00001  0.0  0.0
12   295.0   110.0           0.0            0.00001  0.0  0.0
13   297.5    10.0           0.0            0.00001  0.0  0.0

In [73]:
from datetime import datetime

expiry_date = datetime.strptime(expiries[0], '%Y-%m-%d')
today = datetime.now()

days_to_expiry = (expiry_date - today).days
T = days_to_expiry / 365

T

-0.0027397260273972603

In [74]:
S = get_spot_price("AAPL")
K = 280.0
sigma = 0.500005

In [75]:
from black_scholes import black_scholes_call
from binomial import binomial_price
from monte_carlo import monte_carlo_call

bs_price = black_scholes_call(S=S, K=K,sigma=sigma, r = 0.05, T=T)
bs_price

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\black_scholes.py:21: RuntimeWarning: invalid value encountered in sqrt
  d1 = (np.log(S / K) + (r - q + sigma**2 / 2) * T) / (sigma * np.sqrt(T))
c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\black_scholes.py:22: RuntimeWarning: invalid value encountered in sqrt
  d2 = d1 - sigma * np.sqrt(T)

np.float64(nan)

In [76]:
binomial_price_val = binomial_price(S=S, K=K, r=0.05, sigma=sigma, T=T, N=500, option_type='call', american=True)
binomial_price_val

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\binomial.py:25: RuntimeWarning: invalid value encountered in sqrt
  u = np.exp(sigma * np.sqrt(dt))

np.float64(nan)

In [77]:
mc_price = monte_carlo_call(S=S, K=K, r=0.05, sigma=sigma, T=T, n_simulations=100000, seed=42)
mc_price

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\monte_carlo.py:27: RuntimeWarning: invalid value encountered in sqrt
  S_T = S * np.exp((r - q - sigma**2 / 2) * T + sigma * np.sqrt(T) * Z)

np.float64(nan)

In [78]:
T

-0.0027397260273972603

In [79]:
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-09',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-09',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [80]:
chosen_expiry = expiries[7]
chosen_expiry

'2026-10-02'

In [81]:
chain = aapl.option_chain(chosen_expiry)
liquid_calls = filter_liquid_options(chain.calls)
liquid_calls[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

    strike  bid  ask  volume  openInterest  impliedVolatility
1    230.0  0.0  0.0     1.0             0            0.00001
2    235.0  0.0  0.0     1.0             0            0.00001
3    250.0  0.0  0.0     1.0             0            0.00001
4    255.0  0.0  0.0     1.0             0            0.00001
5    260.0  0.0  0.0     5.0             0            0.00001
6    265.0  0.0  0.0     1.0             0            0.00001
7    270.0  0.0  0.0     1.0             0            0.00001
8    275.0  0.0  0.0     1.0             0            0.00001
9    280.0  0.0  0.0     2.0             0            0.00001
10   285.0  0.0  0.0     9.0             0            0.00001

In [82]:
from datetime import datetime

expiry_date = datetime.strptime(chosen_expiry, '%Y-%m-%d')
today = datetime.now()

days_to_expiry = (expiry_date - today).days
T = days_to_expiry / 365

T

0.08493150684931507

In [83]:
S = get_spot_price("AAPL")
S

319.70001220703125

In [84]:
liquid_calls['distance_from_spot'] = abs(liquid_calls['strike'] - S)
liquid_calls.sort_values('distance_from_spot')[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

    strike  bid  ask  volume  openInterest  impliedVolatility
17   320.0  0.0  0.0   537.0             0           0.000987
16   315.0  0.0  0.0   146.0             0           0.000010
18   325.0  0.0  0.0   439.0             0           0.015635
15   310.0  0.0  0.0   106.0             0           0.000010
19   330.0  0.0  0.0   309.0             0           0.031260
14   305.0  0.0  0.0    42.0             0           0.000010
20   335.0  0.0  0.0   251.0             0           0.031260
13   300.0  0.0  0.0    10.0             0           0.000010
21   340.0  0.0  0.0   306.0             0           0.062509
12   295.0  0.0  0.0    16.0             0           0.000010

In [85]:
K = 320.0
sigma = 0.266945
bid = 11.75
ask = 12.20

In [86]:
from black_scholes import black_scholes_call
from binomial import binomial_price
from monte_carlo import monte_carlo_call

In [87]:
r = 0.05  # placeholder risk-free rate

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T)
binomial_price_val = binomial_price(S=S, K=K, r=r, sigma=sigma, T=T, N=500, option_type='call', american=True)
mc_price = monte_carlo_call(S=S, K=K, r=r, sigma=sigma, T=T, n_simulations=100000, seed=42)

bs_price, binomial_price_val, mc_price

(np.float64(10.440304969338996),
 np.float64(10.439958174848861),
 np.float64(10.464902023325722))

In [88]:
q = 0.0034

bs_price_with_div = black_scholes_call(S=S, K=K, r=0.05, sigma=sigma, T=T, q=q)
binomial_price_with_div = binomial_price(S=S, K=K, r=0.05, sigma=sigma, T=T, N=500, q=q, option_type='call', american=True)
mc_price_with_div = monte_carlo_call(S=S, K=K, r=0.05, sigma=sigma, T=T, q=q, n_simulations=100000, seed=42)

bs_price_with_div, binomial_price_with_div, mc_price_with_div

(np.float64(10.391225081813303),
 np.float64(10.390879995203205),
 np.float64(10.415720953209492))

In [89]:
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-09',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-09',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [90]:
from market_data import get_risk_free_rate
get_risk_free_rate()

0.037300000190734865

In [91]:
import importlib
import market_data

importlib.reload(market_data)

In [92]:
get_risk_free_rate

In [93]:
get_risk_free_rate()

0.037300000190734865

In [94]:
importlib.reload(market_data)

In [95]:
from market_data import get_risk_free_rate
get_risk_free_rate()

0.037300000190734865

In [96]:
import tests.test_real_data_validation

ModuleNotFoundError: No module named 'tests'

In [ ]:
from tests import test_real_data_validation

ModuleNotFoundError: No module named 'tests'

In [ ]:
import importlib
import market_data
importlib.reload(market_data)

In [ ]:
from market_data import get_liquid_near_the_money_contract

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')  # or however you fetched this earlier
r = get_risk_free_rate()
q = 0.0034

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
bs_price

np.float64(8.916706502638277)

In [ ]:
importlib.reload(market_data)

In [ ]:
from market_data import get_liquid_near_the_money_contract, get_risk_free_rate

S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')
r = get_risk_free_rate()
q = 0.0034

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
bs_price

np.float64(8.916706502638277)

In [ ]:
S, K, sigma, T, r

(319.70001220703125,
 320.0,
 0.260749580078125,
 0.0684931506849315,
 0.037300000190734865)

In [ ]:
liquid_calls[['strike', 'bid', 'ask']]  # or re-fetch if this variable isn't still in scope

    strike     bid     ask
0    130.0  188.55  192.30
1    135.0  183.45  187.35
2    140.0  178.50  182.35
3    145.0  173.55  177.40
4    150.0  168.55  172.45
..     ...     ...     ...
74   560.0    0.00    1.03
75   570.0    0.00    1.03
76   580.0    0.00    1.03
77   590.0    0.00    0.01
78   600.0    0.00    0.01

[79 rows x 3 columns]

In [ ]:
r

0.037300000190734865

In [ ]:
from datetime import datetime

# rebuild the same expiry that get_liquid_near_the_money_contract picked
aapl = yf.Ticker("AAPL")
expiries = aapl.options
for expiry in expiries:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    if days_out >= 20:
        chosen_expiry = expiry
        break

chain = aapl.option_chain(chosen_expiry)
chain.calls[chain.calls['strike'] == 320.0][['strike', 'bid', 'ask', 'volume', 'openInterest']]

    strike   bid  ask  volume  openInterest
26   320.0  8.55  8.9   895.0          1621

In [ ]:
from market_data import get_historical_volatality

ImportError: cannot import name 'get_historical_volatality' from 'market_data' (c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\market_data.py)

In [ ]:
importlib.reload(market_data)

In [ ]:
from market_data import get_historical_volatality

In [ ]:
importlib.reload(market_data)

In [ ]:
from market_data import get_historical_volatility

In [ ]:
from market_data import get_historical_volatility
# restart kernel first

hist_vol = get_historical_volatility("AAPL")
hist_vol

0.3274446531289782

In [ ]:
from market_data import get_liquid_near_the_money_contract

In [ ]:
S, K, sigma_implied, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')

hist_vol, sigma_implied

(0.3274446531289782, 0.260749580078125)

In [ ]:
from black_scholes import black_scholes_call

r = get_risk_free_rate()
q = 0.0034

price_with_implied_vol = black_scholes_call(S=S, K=K, r=r, sigma=sigma_implied, T=T, q=q)
price_with_historical_vol = black_scholes_call(S=S, K=K, r=r, sigma=hist_vol, T=T, q=q)

price_with_implied_vol, price_with_historical_vol

(np.float64(8.916706502638277), np.float64(11.138861063506084))

In [ ]:
import black_scholes

In [ ]:
import dashboard
import importlib
importlib.reload(dashboard)

In [ ]:
from dashboard import build_greeks_dashboard
# restart kernel first

S, r, T, chosen_expiry, liquid_contracts = build_greeks_dashboard("AAPL", option_side='calls')

S, r, T, chosen_expiry

ValueError: No sufficiently liquid calls found for 'AAPL'.

In [ ]:
import yfinance as yf
from datetime import datetime

ticker = yf.Ticker("AAPL")
expiries = ticker.options

for expiry in expiries:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    print(expiry, days_out)

2026-08-31 -1
2026-09-02 1
2026-09-04 3
2026-09-09 8
2026-09-11 10
2026-09-18 17
2026-09-25 24
2026-10-02 31
2026-10-09 38
2026-10-16 45
2026-11-20 80
2026-12-18 108
2027-01-15 136
2027-02-19 171
2027-03-19 199
2027-04-16 227
2027-06-17 289
2027-09-17 381
2027-12-17 472
2028-01-21 507
2028-03-17 563
2028-12-15 836

In [ ]:
chosen_expiry = expiries[7]  # whichever one matched >= 20 days from the printout
chain = ticker.option_chain(chosen_expiry)
chain.calls[['strike', 'volume', 'openInterest']].describe()

           strike       volume  openInterest
count   37.000000    36.000000          37.0
mean   323.378378   176.222222           0.0
std     57.167566   581.464167           0.0
min    195.000000     1.000000           0.0
25%    280.000000     2.000000           0.0
50%    325.000000    12.000000           0.0
75%    370.000000    99.250000           0.0
max    415.000000  3475.000000           0.0

In [ ]:
from market_data import filter_liquid_options

test_filtered = filter_liquid_options(chain.calls, min_volume=1, min_open_interest=1)
len(test_filtered)

0

In [97]:
from market_data import get_liquid_near_the_money_contract

S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='puts')
S, K, sigma, T

(319.70001220703125, 320.0, 1.0000000000000003e-05, 0.06575342465753424)