In [1]:
import pandas as pd
pd.__version__

'3.0.5'

In [2]:
from scipy.stats import norm

In [3]:
norm.cdf(0)

np.float64(0.5)

In [4]:
S = 100 
K = 100
r = 0.05
sigma = 0.2
T = 1

In [5]:
import numpy as np

In [6]:
d1 = (np.log(S/K) + (r + sigma**2 / 2)) * T / (sigma * np.sqrt(T))
d2 = d1 - sigma * np.sqrt(T)

d1, d2

(np.float64(0.35000000000000003), np.float64(0.15000000000000002))

In [7]:
N_d1 = norm.cdf(d1)
N_d2 = norm.cdf(d2)

N_d1, N_d2

(np.float64(0.6368306511756191), np.float64(0.5596176923702425))

In [8]:
call_price = S * N_d1 - K * np.exp(-r * T) * N_d2
call_price

np.float64(10.450583572185565)

In [9]:
import sys
sys.path.append('../src')

In [10]:
from black_scholes import black_scholes_call

In [11]:
black_scholes_call(S = 100, K = 100 , sigma = 0.2, r = 0.05, T = 1)

np.float64(10.450583572185565)

In [12]:
import sys
sys.path.append('../src')
from black_scholes import black_scholes_put

In [13]:
from black_scholes import black_scholes_put
black_scholes_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(5.573526022256971)

In [14]:
import importlib
import black_scholes
importlib.reload(black_scholes)
from black_scholes import black_scholes_call, black_scholes_put

In [15]:
from black_scholes import delta_call
from black_scholes import delta_put

In [16]:
delta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(0.6368306511756191)

In [17]:
delta_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-0.3631693488243809)

In [18]:

import importlib
importlib.reload(black_scholes)

In [19]:
from black_scholes import gamma

In [20]:
gamma(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(0.018762017345846895)

In [21]:
import importlib
importlib.reload(black_scholes)
from black_scholes import vega

In [22]:
vega(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(37.52403469169379)

In [23]:
vega(S=100, K=150, r=0.05, sigma=0.2, T=1)

np.float64(9.772000145726361)

In [24]:
import importlib
importlib.reload(black_scholes)

In [25]:
from black_scholes import theta_call
theta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-6.414027546438197)

In [26]:
import importlib
importlib.reload(black_scholes)

In [27]:
from black_scholes import rho_call
rho_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(53.232481545376345)

In [28]:
from black_scholes import rho_put
rho_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-41.89046090469506)

In [29]:
import importlib

In [30]:
importlib.reload(black_scholes)

In [31]:
from black_scholes import delta_call_numerical, delta_call

In [32]:
numerical = delta_call_numerical(S=100, K=100, r=0.05, sigma=0.2, T=1)
analytical = delta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

numerical, analytical

(np.float64(0.6368306425763137), np.float64(0.6368306511756191))

In [33]:
import importlib
importlib.reload(black_scholes)

In [34]:
from black_scholes import gamma_numerical
gamma_numerical(S=100, K=100, r=0.05, sigma=0.2, T=1, h=0.0001)

np.float64(0.018761880937745445)

In [35]:
import sys, os
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))

In [36]:
from binomial import binomial_price
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=3, q=0)

np.float64(11.043871091951113)

In [37]:
from binomial import binomial_price
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=2, q=0, option_type='call', american=False)

np.float64(9.540501338582947)

In [38]:
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=100, q=0, option_type='call', american=False)

np.float64(10.430611662249113)

In [39]:
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='call', american=False)

np.float64(10.44658513644654)

In [40]:
import importlib
importlib.reload(black_scholes)

In [41]:
# American put, deep in-the-money — early exercise should add real value here
binomial_price(S=80, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='put', american=True)

np.float64(20.0)

In [42]:
binomial_price(S=80, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='put', american=False)

np.float64(16.983137118259393)

In [43]:
from monte_carlo import monte_carlo_call
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=5, seed=42)

np.float64(13.522454507401847)

In [44]:
from monte_carlo import monte_carlo_call
# restart kernel first

monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=5, seed=42)

np.float64(13.522454507401847)

In [45]:
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=100000, seed=42)

np.float64(10.47389196070258)

In [46]:
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=1000000, seed=42)

np.float64(10.434157688982824)

In [47]:
# Run 100,000 sims five separate times (no fixed seed) — watch how much they vary
[monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=1000000) for _ in range(5)]

[np.float64(10.459202124096821),
 np.float64(10.452150509799127),
 np.float64(10.450558888427537),
 np.float64(10.456686428080205),
 np.float64(10.438973533748085)]

In [48]:
from monte_carlo import monte_carlo_call, monte_carlo_call_antithetic
# restart kernel first

[monte_carlo_call_antithetic(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=1000000, seed=42) for _ in range(5)]

[np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086)]

In [49]:
# Plain Monte Carlo — 5 runs, small n_simulations to make spread visible
[monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000) for _ in range(5)]

[np.float64(10.367033313398208),
 np.float64(10.610462259003915),
 np.float64(10.309140256582728),
 np.float64(10.380410291111975),
 np.float64(10.55075981829986)]

In [50]:
# Antithetic — same n_simulations, 5 runs
[monte_carlo_call_antithetic(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000) for _ in range(5)]

[np.float64(10.6240416300026),
 np.float64(10.546187221169946),
 np.float64(10.450979180137036),
 np.float64(10.479650982262912),
 np.float64(10.480538365483373)]

In [51]:
from monte_carlo import monte_carlo_call_control_variate
[monte_carlo_call_control_variate(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000)for _ in range(5)]

[np.float64(10.451839876232127),
 np.float64(10.45647104530929),
 np.float64(10.448927776987459),
 np.float64(10.454923225108473),
 np.float64(10.417638670537002)]

In [52]:
import yfinance as yf
reliance = yf.Ticker("RELIANCE.NS")
reliance.info

{'address1': 'Maker Chambers IV',
 'address2': '3rd Floor 222 Nariman Point',
 'city': 'Mumbai',
 'zip': '400021',
 'country': 'India',
 'phone': '91 22 3555 5000',
 'fax': '91 22 2204 2268',
 'website': 'https://www.ril.com',
 'industry': 'Oil & Gas Refining & Marketing',
 'industryKey': 'oil-gas-refining-marketing',
 'industryDisp': 'Oil & Gas Refining & Marketing',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Reliance Industries Limited engages in hydrocarbon exploration and production, petroleum refining and marketing, petrochemicals, advanced materials and composites, renewable, financial services, retail, and digital services worldwide. It operates through the Oil to Chemicals, Oil and Gas, Retail, Digital Services, and Others segments. The company is involved in refining and marketing products, including liquefied petroleum gas, propylene, naphtha, gasoline, jet/aviation turbine fuel, kerosine oil, diesel, sulfur, and petroleum coke. It also provides polymers comprising high-density and low-density polyethylene (PE), linear low-density PE, homopolymer, random and impact copolymer, and polyvinyl chloride; fiber intermediates that include purified terephthalic acid, and ethylene glycols and oxide; aromatics, such as paraxylene, ortho xylene, benzene, and linear alkyl benzene and paraffin; and textiles that consist of fabrics, apparel, and auto furnishings. In addition, the company offers elastomers, such as polybutadiene rubber, styrene butadiene rubber, and butyl rubber; fiber and yarn polyesters; and bioenergy solutions, including compressed biogas, and pellets and briquettes. Further, it engages in oil and gas exploration and production activities; operation of various stores comprising supermarkets, hypermarket, wholesale cash and carry, specialty, and online stores; operation of media and entertainment platforms, and Network18 and television channels; and publishing of magazines. Additionally, the company provides highway hospitality and fleet management services, as well as digital services, such as connectivity, fiber, mobile devices, apps, business, and other digital solutions. Reliance Industries Limited was founded in 1957 and is based in Mumbai, India.',
 'fullTimeEmployees': 404501,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Mukesh Dhirubhai Ambani',
   'age': 68,
   'title': 'Chairman & MD',
   'yearBorn': 1957,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nikhil Rasiklal Meswani',
   'age': 59,
   'title': 'Executive Director',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hital Rasiklal Meswani',
   'age': 57,
   'title': 'Executive Director',
   'yearBorn': 1968,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Panda Madhusudana Siva Prasad',
   'age': 73,
   'title': 'Executive Director',
   'yearBorn': 1952,
   'fiscalYear': 2026,
   'totalPay': 205800000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anant Mukesh Ambani',
   'age': 30,
   'title': 'Whole-Time Director',
   'yearBorn': 1995,
   'fiscalYear': 2026,
   'totalPay': 123900000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Parul  Sharma',
   'title': 'Group President',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Srikanth  Venkatachari',
   'age': 59,
   'title': 'Chief Financial Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mahesh  Marve',
   'title': 'Head of Research & Technology',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hemen Kanu Modi',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Savithri  Parekh',
   'age': 59,
   'title': 'Company Secretary & Compliance Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 9,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 10,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1798675200,
 'irWebsite': 'http://ril.com/html/investor/investor.html',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1282.2,
 'open': 1284.9,
 'dayLow': 1280.0,
 'dayHigh': 1291.8,
 'regularMarketPreviousClose': 1282.2,
 'regularMarketOpen': 1284.9,
 'regularMarketDayLow': 1280.0,
 'regularMarketDayHigh': 1291.8,
 'dividendRate': 6.0,
 'dividendYield': 0.47,
 'exDividendDate': 1780617600,
 'payoutRatio': 0.2083,
 'fiveYearAvgDividendYield': 0.44,
 'beta': 0.157,
 'trailingPE': 23.20173,
 'forwardPE': 18.008951,
 'volume': 6826848,
 'regularMarketVolume': 6826848,
 'averageVolume': 12831951,
 'averageVolume10days': 8027361,
 'averageDailyVolume10Day': 8027361,
 'bid': 0.0,
 'ask': 0.0,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 17416291614720,
 'nonDilutedMarketCap': 17351336411314,
 'fiftyTwoWeekLow': 1249.8,
 'fiftyTwoWeekHigh': 1611.8,
 'allTimeHigh': 1611.8,
 'allTimeLow': 5.428648,
 'fulldayPrice': 1287.0,
 'priceToSalesTrailing12Months': 1.5418037,
 'fiftyDayAverage': 1304.352,
 'twoHundredDayAverage': 1388.9225,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'INR',
 'tradeable': False,
 'enterpriseValue': 20633182273536,
 'profitMargins': 0.066149995,
 'floatShares': 6638895750,
 'sharesOutstanding': 13532472634,
 'heldPercentInsiders': 0.51798,
 'heldPercentInstitutions': 0.28070998,
 'impliedSharesOutstanding': 13532472635,
 'bookValue': 668.045,
 'priceToBook': 1.926517,
 'lastFiscalYearEnd': 1774915200,
 'nextFiscalYearEnd': 1806451200,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': -0.224,
 'netIncomeToCommon': 747269980160,
 'trailingEps': 55.47,
 'forwardEps': 71.46446,
 'pegRatio': 0.82,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1730073600,
 'enterpriseToRevenue': 1.827,
 'enterpriseToEbitda': 11.423,
 '52WeekChange': -0.049412787,
 'SandP52WeekChange': 0.20204377,
 'lastDividendValue': 6.0,
 'lastDividendDate': 1780617600,
 'quoteType': 'EQUITY',
 'currentPrice': 1287.0,
 'targetHighPrice': 1890.0,
 'targetLowPrice': 1350.0,
 'targetMeanPrice': 1677.8889,
 'targetMedianPrice': 1690.0,
 'recommendationMean': 1.30769,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 27,
 'totalCash': 2581470117888,
 'totalCashPerShare': 190.761,
 'ebitda': 1806359986176,
 'totalDebt': 3979999969280,
 'totalRevenue': 11296050249728,
 'debtToEquity': 36.653,
 'revenuePerShare': 834.734,
 'grossProfits': 3822279983104,
 'earningsGrowth': -0.224,
 'revenueGrowth': 0.297,
 'grossMargins': 0.33837003,
 'ebitdaMargins': 0.15991001,
 'operatingMargins': 0.12331,
 'financialCurrency': 'INR',
 'symbol': 'RELIANCE.NS',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'regularMarketChangePercent': 0.3743604,
 'regularMarketPrice': 1287.0,
 'shortName': 'RELIANCE INDUSTRIES LTD',
 'longName': 'Reliance Industries Limited',
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 820467900000,
 'regularMarketChange': 4.800049,
 'fulldayChange': 4.800049,
 'fulldayChangePercent': 0.3743604,
 'regularMarketDayRange': '1280.0 - 1291.8',
 'fullExchangeName': 'NSE',
 'averageDailyVolume3Month': 12831951,
 'fiftyTwoWeekLowChange': 37.19995,
 'fiftyTwoWeekLowChangePercent': 0.029764723,
 'fiftyTwoWeekRange': '1249.8 - 1611.8',
 'fiftyTwoWeekHighChange': -324.80005,
 'fiftyTwoWeekHighChangePercent': -0.20151386,
 'corporateActions': [],
 'regularMarketTime': 1787910305,
 'exchange': 'NSI',
 'messageBoardId': 'finmb_878373',
 'exchangeTimezoneName': 'Asia/Kolkata',
 'exchangeTimezoneShortName': 'IST',
 'gmtOffSetMilliseconds': 19800000,
 'market': 'in_market',
 'esgPopulated': False,
 'fiftyTwoWeekChangePercent': -4.9412785,
 'earningsTimestamp': 1784282400,
 'earningsTimestampStart': 1792144800,
 'earningsTimestampEnd': 1792144800,
 'earningsCallTimestampStart': 1745592300,
 'earningsCallTimestampEnd': 1745592300,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 55.47,
 'epsForward': 71.46446,
 'epsCurrentYear': 64.0101,
 'priceEpsCurrentYear': 20.106201,
 'fiftyDayAverageChange': -17.35205,
 'fiftyDayAverageChangePercent': -0.013303196,
 'twoHundredDayAverageChange': -101.922485,
 'twoHundredDayAverageChangePercent': -0.073382415,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'trailingPegRatio': None}

In [53]:
reliance = yf.Ticker("RELIANCE.NS")
price = reliance.info['currentPrice']
price

1287.0

In [54]:
history = reliance.history(period="1d")
history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-28 00:00:00+05:30,1284.900024,1291.800049,1280.0,1287.0,6830228,0.0,0.0

In [55]:
latest_price = history['Close'].iloc[-1]
latest_price

np.float64(1287.0)

In [56]:
history = reliance.history(period = "1d")
latest_price = history['Close'].iloc[-1]
latest_price

np.float64(1287.0)

In [58]:
from market_data import get_spot_price
get_spot_price("RELIANCE.NS")

1287.0

In [61]:
get_spot_price("SILVERBEES.NS")

230.4199981689453

In [63]:
get_spot_price("AAPL")

319.70001220703125

In [68]:
reliance = yf.Ticker("RELIANCE.NS")
expiries = reliance.options
expiries

()

In [69]:
nifty = yf.Ticker("^NSEI")
nifty.options

()

In [70]:
tcs = yf.Ticker("TCS.NS")
tcs.options

()

In [71]:
aapl = yf.Ticker("AAPL")
expiries = aapl.options
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [72]:
chain = aapl.option_chain(expiries[0])
chain.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:44+00:00,225.0,95.54,92.70,96.55,10.410004,12.228361,2.0,2,3.170901,True,REGULAR,USD
1,AAPL260831C00235000,2026-08-17 18:05:20+00:00,235.0,68.01,82.95,86.55,0.000000,0.000000,NaN,0,1.609377,True,REGULAR,USD
2,AAPL260831C00240000,2026-08-17 18:05:20+00:00,240.0,63.00,77.90,81.55,0.000000,0.000000,NaN,0,1.406253,True,REGULAR,USD
3,AAPL260831C00250000,2026-08-20 14:33:30+00:00,250.0,66.80,67.85,71.55,0.000000,0.000000,NaN,1,0.500005,True,REGULAR,USD
4,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,42.95,46.55,0.000000,0.000000,1.0,2,0.847658,True,REGULAR,USD
5,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,37.90,41.50,4.520001,12.914287,2.0,3,0.500005,True,REGULAR,USD
6,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,35.45,38.50,5.049999,15.781248,7.0,12,1.285160,True,REGULAR,USD
7,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,32.95,36.50,8.750000,33.836040,7.0,14,0.613285,True,REGULAR,USD
8,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,30.70,34.05,9.970001,44.990982,4.0,17,0.746096,True,REGULAR,USD
9,AAPL260831C00290000,2026-08-28 14:14:28+00:00,290.0,26.38,28.65,31.35,6.229999,30.918112,2.0,38,0.765627,True,REGULAR,USD
10,AAPL260831C00292500,2026-08-25 19:52:33+00:00,292.5,17.15,25.45,29.05,0.000000,0.000000,213.0,50,0.531255,True,REGULAR,USD
11,AAPL260831C00295000,2026-08-28 19:47:08+00:00,295.0,25.07,22.95,26.55,9.650000,62.581062,110.0,40,1.047856,True,REGULAR,USD
12,AAPL260831C00297500,2026-08-28 16:02:06+00:00,297.5,23.78,20.55,23.60,9.330001,64.567480,10.0,21,0.887208,True,REGULAR,USD
13,AAPL260831C00300000,2026-08-28 18:14:24+00:00,300.0,19.84,17.95,21.55,5.640000,39.718310,6.0,98,0.896241,True,REGULAR,USD
14,AAPL260831C00302500,2026-08-28 13:46:02+00:00,302.5,13.65,16.35,19.10,1.940000,16.567034,4.0,66,0.554692,True,REGULAR,USD
15,AAPL260831C00305000,2026-08-28 19:35:13+00:00,305.0,15.08,13.70,16.25,5.269999,53.720684,10.0,331,0.691898,True,REGULAR,USD
16,AAPL260831C00307500,2026-08-28 19:59:51+00:00,307.5,10.95,11.05,13.10,3.190000,41.108242,71.0,366,0.504399,True,REGULAR,USD
17,AAPL260831C00310000,2026-08-28 19:53:16+00:00,310.0,10.00,9.40,10.15,4.500000,81.818184,481.0,1256,0.346198,True,REGULAR,USD
18,AAPL260831C00312500,2026-08-28 19:57:34+00:00,312.5,7.65,7.05,7.80,3.850000,101.315796,567.0,949,0.307624,True,REGULAR,USD
19,AAPL260831C00315000,2026-08-28 19:58:41+00:00,315.0,5.25,4.85,5.15,2.810000,115.163930,6777.0,6572,0.209969,True,REGULAR,USD
20,AAPL260831C00317500,2026-08-28 19:59:32+00:00,317.5,3.05,2.77,3.10,1.650000,117.857150,14265.0,2342,0.190194,True,REGULAR,USD
21,AAPL260831C00320000,2026-08-28 19:59:58+00:00,320.0,1.40,1.40,1.58,0.600000,74.999990,32256.0,4387,0.182625,False,REGULAR,USD
22,AAPL260831C00322500,2026-08-28 19:59:55+00:00,322.5,0.69,0.55,0.69,0.240000,53.333336,25298.0,2478,0.183846,False,REGULAR,USD
23,AAPL260831C00325000,2026-08-28 19:59:55+00:00,325.0,0.27,0.25,0.28,0.050000,22.727278,21611.0,3280,0.191903,False,REGULAR,USD
24,AAPL260831C00327500,2026-08-28 19:59:49+00:00,327.5,0.13,0.11,0.14,-0.020000,-13.333340,5805.0,358,0.212898,False,REGULAR,USD
25,AAPL260831C00330000,2026-08-28 19:59:40+00:00,330.0,0.08,0.06,0.08,0.000000,0.000000,7447.0,1598,0.237312,False,REGULAR,USD
26,AAPL260831C00332500,2026-08-28 19:59:27+00:00,332.5,0.05,0.03,0.05,0.010000,25.000006,833.0,200,0.261726,False,REGULAR,USD
27,AAPL260831C00335000,2026-08-28 19:58:46+00:00,335.0,0.03,0.02,0.03,0.000000,0.000000,479.0,406,0.281257,False,REGULAR,USD
28,AAPL260831C00337500,2026-08-28 19:31:25+00:00,337.5,0.02,0.01,0.03,0.000000,0.000000,856.0,150,0.320319,False,REGULAR,USD
29,AAPL260831C00340000,2026-08-28 19:40:08+00:00,340.0,0.03,0.01,0.03,0.010000,50.000000,88.0,1045,0.359381,False,REGULAR,USD
30,AAPL260831C00342500,2026-08-28 17:31:44+00:00,342.5,0.01,0.00,0.05,0.000000,0.000000,8.0,65,0.421881,False,REGULAR,USD
31,AAPL260831C00345000,2026-08-28 16:34:49+00:00,345.0,0.03,0.00,0.52,0.020000,200.000000,74.0,169,0.599613,False,REGULAR,USD
32,AAPL260831C00350000,2026-08-28 18:09:22+00:00,350.0,0.01,0.00,0.01,0.000000,0.000000,2.0,140,0.445318,False,REGULAR,USD
33,AAPL260831C00355000,2026-08-26 19:14:51+00:00,355.0,0.01,0.00,0.02,0.000000,0.000000,76.0,196,0.507817,False,REGULAR,USD
34,AAPL260831C00360000,2026-08-27 16:41:21+00:00,360.0,0.01,0.00,1.02,0.000000,0.000000,2.0,12,0.974610,False,REGULAR,USD
35,AAPL260831C00365000,2026-08-21 18:59:47+00:00,365.0,0.07,0.00,1.03,0.000000,0.000000,6.0,6,1.064458,False,REGULAR,USD
36,AAPL260831C00370000,2026-08-21 19:00:54+00:00,370.0,0.07,0.00,1.02,0.000000,0.000000,26.0,26,1.148442,False,REGULAR,USD
37,AAPL260831C00375000,2026-08-25 14:43:57+00:00,375.0,0.02,0.00,1.02,0.000000,0.000000,2.0,4,1.231449,False,REGULAR,USD
38,AAPL260831C00380000,2026-08-28 14:45:09+00:00,380.0,0.01,0.00,1.02,-0.100000,-90.909096,3.0,3,1.312503,False,REGULAR,USD
39,AAPL260831C00385000,2026-08-28 15:58:14+00:00,385.0,0.01,0.00,1.02,-0.020000,-66.666670,1.0,2,1.391605,False,REGULAR,USD

In [73]:
from market_data import get_spot_price
get_spot_price("AAPL")

319.70001220703125

In [75]:
chain.calls.shape

(40, 14)

In [76]:
chain.calls.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='str')

In [79]:
chain.calls.head(10)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:44+00:00,225.0,95.54,92.70,96.55,10.410004,12.228361,2.0,2,3.170901,True,REGULAR,USD
1,AAPL260831C00235000,2026-08-17 18:05:20+00:00,235.0,68.01,82.95,86.55,0.000000,0.000000,NaN,0,1.609377,True,REGULAR,USD
2,AAPL260831C00240000,2026-08-17 18:05:20+00:00,240.0,63.00,77.90,81.55,0.000000,0.000000,NaN,0,1.406253,True,REGULAR,USD
3,AAPL260831C00250000,2026-08-20 14:33:30+00:00,250.0,66.80,67.85,71.55,0.000000,0.000000,NaN,1,0.500005,True,REGULAR,USD
4,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,42.95,46.55,0.000000,0.000000,1.0,2,0.847658,True,REGULAR,USD
5,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,37.90,41.50,4.520001,12.914287,2.0,3,0.500005,True,REGULAR,USD
6,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,35.45,38.50,5.049999,15.781248,7.0,12,1.285160,True,REGULAR,USD
7,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,32.95,36.50,8.750000,33.836040,7.0,14,0.613285,True,REGULAR,USD
8,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,30.70,34.05,9.970001,44.990982,4.0,17,0.746096,True,REGULAR,USD
9,AAPL260831C00290000,2026-08-28 14:14:28+00:00,290.0,26.38,28.65,31.35,6.229999,30.918112,2.0,38,0.765627,True,REGULAR,USD

In [81]:
import importlib
import market_data

importlib.reload(market_data)

In [83]:
from market_data import filter_liquid_options

liquid_calls = filter_liquid_options(chain.calls)
liquid_calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:44+00:00,225.0,95.54,92.70,96.55,10.410004,12.228361,2.0,2,3.170901,True,REGULAR,USD
4,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,42.95,46.55,0.000000,0.000000,1.0,2,0.847658,True,REGULAR,USD
5,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,37.90,41.50,4.520001,12.914287,2.0,3,0.500005,True,REGULAR,USD
6,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,35.45,38.50,5.049999,15.781248,7.0,12,1.285160,True,REGULAR,USD
7,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,32.95,36.50,8.750000,33.836040,7.0,14,0.613285,True,REGULAR,USD
8,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,30.70,34.05,9.970001,44.990982,4.0,17,0.746096,True,REGULAR,USD
9,AAPL260831C00290000,2026-08-28 14:14:28+00:00,290.0,26.38,28.65,31.35,6.229999,30.918112,2.0,38,0.765627,True,REGULAR,USD
10,AAPL260831C00292500,2026-08-25 19:52:33+00:00,292.5,17.15,25.45,29.05,0.000000,0.000000,213.0,50,0.531255,True,REGULAR,USD
11,AAPL260831C00295000,2026-08-28 19:47:08+00:00,295.0,25.07,22.95,26.55,9.650000,62.581062,110.0,40,1.047856,True,REGULAR,USD
12,AAPL260831C00297500,2026-08-28 16:02:06+00:00,297.5,23.78,20.55,23.60,9.330001,64.567480,10.0,21,0.887208,True,REGULAR,USD
13,AAPL260831C00300000,2026-08-28 18:14:24+00:00,300.0,19.84,17.95,21.55,5.640000,39.718310,6.0,98,0.896241,True,REGULAR,USD
14,AAPL260831C00302500,2026-08-28 13:46:02+00:00,302.5,13.65,16.35,19.10,1.940000,16.567034,4.0,66,0.554692,True,REGULAR,USD
15,AAPL260831C00305000,2026-08-28 19:35:13+00:00,305.0,15.08,13.70,16.25,5.269999,53.720684,10.0,331,0.691898,True,REGULAR,USD
16,AAPL260831C00307500,2026-08-28 19:59:51+00:00,307.5,10.95,11.05,13.10,3.190000,41.108242,71.0,366,0.504399,True,REGULAR,USD
17,AAPL260831C00310000,2026-08-28 19:53:16+00:00,310.0,10.00,9.40,10.15,4.500000,81.818184,481.0,1256,0.346198,True,REGULAR,USD
18,AAPL260831C00312500,2026-08-28 19:57:34+00:00,312.5,7.65,7.05,7.80,3.850000,101.315796,567.0,949,0.307624,True,REGULAR,USD
19,AAPL260831C00315000,2026-08-28 19:58:41+00:00,315.0,5.25,4.85,5.15,2.810000,115.163930,6777.0,6572,0.209969,True,REGULAR,USD
20,AAPL260831C00317500,2026-08-28 19:59:32+00:00,317.5,3.05,2.77,3.10,1.650000,117.857150,14265.0,2342,0.190194,True,REGULAR,USD
21,AAPL260831C00320000,2026-08-28 19:59:58+00:00,320.0,1.40,1.40,1.58,0.600000,74.999990,32256.0,4387,0.182625,False,REGULAR,USD
22,AAPL260831C00322500,2026-08-28 19:59:55+00:00,322.5,0.69,0.55,0.69,0.240000,53.333336,25298.0,2478,0.183846,False,REGULAR,USD
23,AAPL260831C00325000,2026-08-28 19:59:55+00:00,325.0,0.27,0.25,0.28,0.050000,22.727278,21611.0,3280,0.191903,False,REGULAR,USD
24,AAPL260831C00327500,2026-08-28 19:59:49+00:00,327.5,0.13,0.11,0.14,-0.020000,-13.333340,5805.0,358,0.212898,False,REGULAR,USD
25,AAPL260831C00330000,2026-08-28 19:59:40+00:00,330.0,0.08,0.06,0.08,0.000000,0.000000,7447.0,1598,0.237312,False,REGULAR,USD
26,AAPL260831C00332500,2026-08-28 19:59:27+00:00,332.5,0.05,0.03,0.05,0.010000,25.000006,833.0,200,0.261726,False,REGULAR,USD
27,AAPL260831C00335000,2026-08-28 19:58:46+00:00,335.0,0.03,0.02,0.03,0.000000,0.000000,479.0,406,0.281257,False,REGULAR,USD
28,AAPL260831C00337500,2026-08-28 19:31:25+00:00,337.5,0.02,0.01,0.03,0.000000,0.000000,856.0,150,0.320319,False,REGULAR,USD
29,AAPL260831C00340000,2026-08-28 19:40:08+00:00,340.0,0.03,0.01,0.03,0.010000,50.000000,88.0,1045,0.359381,False,REGULAR,USD
30,AAPL260831C00342500,2026-08-28 17:31:44+00:00,342.5,0.01,0.00,0.05,0.000000,0.000000,8.0,65,0.421881,False,REGULAR,USD
31,AAPL260831C00345000,2026-08-28 16:34:49+00:00,345.0,0.03,0.00,0.52,0.020000,200.000000,74.0,169,0.599613,False,REGULAR,USD
32,AAPL260831C00350000,2026-08-28 18:09:22+00:00,350.0,0.01,0.00,0.01,0.000000,0.000000,2.0,140,0.445318,False,REGULAR,USD
33,AAPL260831C00355000,2026-08-26 19:14:51+00:00,355.0,0.01,0.00,0.02,0.000000,0.000000,76.0,196,0.507817,False,REGULAR,USD
34,AAPL260831C00360000,2026-08-27 16:41:21+00:00,360.0,0.01,0.00,1.02,0.000000,0.000000,2.0,12,0.974610,False,REGULAR,USD
35,AAPL260831C00365000,2026-08-21 18:59:47+00:00,365.0,0.07,0.00,1.03,0.000000,0.000000,6.0,6,1.064458,False,REGULAR,USD
36,AAPL260831C00370000,2026-08-21 19:00:54+00:00,370.0,0.07,0.00,1.02,0.000000,0.000000,26.0,26,1.148442,False,REGULAR,USD
37,AAPL260831C00375000,2026-08-25 14:43:57+00:00,375.0,0.02,0.00,1.02,0.000000,0.000000,2.0,4,1.231449,False,REGULAR,USD
38,AAPL260831C00380000,2026-08-28 14:45:09+00:00,380.0,0.01,0.00,1.02,-0.100000,-90.909096,3.0,3,1.312503,False,REGULAR,USD
39,AAPL260831C00385000,2026-08-28 15:58:14+00:00,385.0,0.01,0.00,1.02,-0.020000,-66.666670,1.0,2,1.391605,False,REGULAR,USD

In [84]:
liquid_calls.shape

(37, 14)

In [86]:
liquid_calls[['strike', 'volume', 'openInterest', 'impliedVolatility', 'bid', 'ask']].head(10)

    strike  volume  openInterest  impliedVolatility    bid    ask
0    225.0     2.0             2           3.170901  92.70  96.55
4    275.0     1.0             2           0.847658  42.95  46.55
5    280.0     2.0             3           0.500005  37.90  41.50
6    282.5     7.0            12           1.285160  35.45  38.50
7    285.0     7.0            14           0.613285  32.95  36.50
8    287.5     4.0            17           0.746096  30.70  34.05
9    290.0     2.0            38           0.765627  28.65  31.35
10   292.5   213.0            50           0.531255  25.45  29.05
11   295.0   110.0            40           1.047856  22.95  26.55
12   297.5    10.0            21           0.887208  20.55  23.60

In [93]:
from datetime import datetime

expiry_date = datetime.strptime(expiries[0], '%Y-%m-%d')
today = datetime.now()

days_to_expiry = (expiry_date - today).days
T = days_to_expiry / 365

T

0.0

In [ ]:
S = get_spot_price("AAPL")
K = 280.0
sigma = 0.500005

In [95]:
from black_scholes import black_scholes_call
from binomial import binomial_price
from monte_carlo import monte_carlo_call

bs_price = black_scholes_call(S=S, K=K,sigma=sigma, r = 0.05, T=T)
bs_price

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\black_scholes.py:21: RuntimeWarning: divide by zero encountered in scalar divide
  d1 = (np.log(S / K) + (r - q + sigma**2 / 2) * T) / (sigma * np.sqrt(T))

np.float64(39.70001220703125)

In [96]:
binomial_price_val = binomial_price(S=S, K=K, r=0.05, sigma=sigma, T=T, N=500, option_type='call', american=True)
binomial_price_val

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\binomial.py:27: RuntimeWarning: invalid value encountered in scalar divide
  p = (np.exp((r - q) * dt) - d) / (u - d)

np.float64(nan)

In [103]:
mc_price = monte_carlo_call(S=S, K=K, r=0.05, sigma=sigma, T=T, n_simulations=100000, seed=42)
mc_price

np.float64(39.70001220703125)

In [104]:
T

0.0

In [105]:
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [107]:
chosen_expiry = expiries[7]
chosen_expiry

'2026-10-16'

In [109]:
chain = aapl.option_chain(chosen_expiry)
liquid_calls = filter_liquid_options(chain.calls)
liquid_calls[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

   strike     bid     ask  volume  openInterest  impliedVolatility
0   130.0  188.55  192.30      36            34           1.230473
1   135.0  183.45  187.35       1            61           1.176274
2   140.0  178.50  182.35      34            22           1.137211
3   145.0  173.55  177.40       9            18           1.104497
4   150.0  168.55  172.45       3            15           1.066899
5   155.0  163.60  167.45       2            60           1.030522
6   160.0  158.70  162.50       3           228           1.004400
7   165.0  153.65  157.50       1            81           0.959961
8   170.0  148.70  152.55       1            59           0.930176
9   175.0  143.70  147.60       2            25           0.896485

In [110]:
from datetime import datetime

expiry_date = datetime.strptime(chosen_expiry, '%Y-%m-%d')
today = datetime.now()

days_to_expiry = (expiry_date - today).days
T = days_to_expiry / 365

T

0.12602739726027398

In [112]:
S = get_spot_price("AAPL")
S

319.70001220703125

In [113]:
liquid_calls['distance_from_spot'] = abs(liquid_calls['strike'] - S)
liquid_calls.sort_values('distance_from_spot')[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

    strike    bid    ask  volume  openInterest  impliedVolatility
38   320.0  11.75  12.20    3380         11820           0.266945
37   315.0  14.50  14.90    1405         10880           0.270332
39   325.0   9.35   9.60    1328          8894           0.258796
36   310.0  17.60  18.10    1167         11206           0.278083
40   330.0   7.25   7.55    2958         15383           0.255501
35   305.0  20.75  21.70     191          6774           0.289009
41   335.0   5.60   5.80     751          8524           0.251808
34   300.0  24.40  25.70     408         15928           0.304633
42   340.0   4.25   4.45    1770         13632           0.250740
33   295.0  28.65  29.95      36          2170           0.322822

In [114]:
K = 320.0
sigma = 0.266945
bid = 11.75
ask = 12.20

In [115]:
from black_scholes import black_scholes_call
from binomial import binomial_price
from monte_carlo import monte_carlo_call

In [116]:
r = 0.05  # placeholder risk-free rate

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T)
binomial_price_val = binomial_price(S=S, K=K, r=r, sigma=sigma, T=T, N=500, option_type='call', american=True)
mc_price = monte_carlo_call(S=S, K=K, r=r, sigma=sigma, T=T, n_simulations=100000, seed=42)

bs_price, binomial_price_val, mc_price

(np.float64(12.924178187173027),
 np.float64(12.922871862082792),
 np.float64(12.954709418630221))

In [117]:
q = 0.0034

bs_price_with_div = black_scholes_call(S=S, K=K, r=0.05, sigma=sigma, T=T, q=q)
binomial_price_with_div = binomial_price(S=S, K=K, r=0.05, sigma=sigma, T=T, N=500, q=q, option_type='call', american=True)
mc_price_with_div = monte_carlo_call(S=S, K=K, r=0.05, sigma=sigma, T=T, q=q, n_simulations=100000, seed=42)

bs_price_with_div, binomial_price_with_div, mc_price_with_div

(np.float64(12.850149949607783),
 np.float64(12.848846757254586),
 np.float64(12.880532858292899))

np.float64(11.276999145026082)

In [119]:
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [122]:
from market_data import get_risk_free_rate
get_risk_free_rate()

ImportError: cannot import name 'get_risk_free_rate' from 'market_data' (c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\market_data.py)

In [123]:
import importlib
import market_data

importlib.reload(market_data)

In [124]:
get_risk_free_rate

NameError: name 'get_risk_free_rate' is not defined

In [125]:
get_risk_free_rate()

NameError: name 'get_risk_free_rate' is not defined

In [128]:
importlib.reload(market_data)

In [129]:
from market_data import get_risk_free_rate
get_risk_free_rate()

0.037300000190734865

In [133]:
import tests.test_real_data_validation

ModuleNotFoundError: No module named 'tests'

In [134]:
from tests import test_real_data_validation

ModuleNotFoundError: No module named 'tests'

In [135]:
import importlib
import market_data
importlib.reload(market_data)

In [136]:
from market_data import get_liquid_near_the_money_contract

In [142]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')  # or however you fetched this earlier
r = get_risk_free_rate()
q = 0.0034

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
bs_price

np.float64(8.916706502638277)

In [140]:
importlib.reload(market_data)

In [143]:
from market_data import get_liquid_near_the_money_contract, get_risk_free_rate

S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')
r = get_risk_free_rate()
q = 0.0034

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
bs_price

np.float64(8.916706502638277)

In [144]:
S, K, sigma, T, r

(319.70001220703125,
 320.0,
 0.260749580078125,
 0.0684931506849315,
 0.037300000190734865)

In [145]:
liquid_calls[['strike', 'bid', 'ask']]  # or re-fetch if this variable isn't still in scope

    strike     bid     ask
0    130.0  188.55  192.30
1    135.0  183.45  187.35
2    140.0  178.50  182.35
3    145.0  173.55  177.40
4    150.0  168.55  172.45
..     ...     ...     ...
74   560.0    0.00    1.03
75   570.0    0.00    1.03
76   580.0    0.00    1.03
77   590.0    0.00    0.01
78   600.0    0.00    0.01

[79 rows x 3 columns]

In [146]:
r

0.037300000190734865

In [147]:
from datetime import datetime

# rebuild the same expiry that get_liquid_near_the_money_contract picked
aapl = yf.Ticker("AAPL")
expiries = aapl.options
for expiry in expiries:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    if days_out >= 20:
        chosen_expiry = expiry
        break

chain = aapl.option_chain(chosen_expiry)
chain.calls[chain.calls['strike'] == 320.0][['strike', 'bid', 'ask', 'volume', 'openInterest']]

    strike   bid  ask  volume  openInterest
26   320.0  8.55  8.9   895.0          1621