In [3]:
import pandas as pd
pd.__version__

'3.0.5'

In [4]:
from scipy.stats import norm

In [5]:
norm.cdf(0)

np.float64(0.5)

In [6]:
S = 100 
K = 100
r = 0.05
sigma = 0.2
T = 1

In [7]:
import numpy as np

In [8]:
d1 = (np.log(S/K) + (r + sigma**2 / 2)) * T / (sigma * np.sqrt(T))
d2 = d1 - sigma * np.sqrt(T)

d1, d2

(np.float64(0.35000000000000003), np.float64(0.15000000000000002))

In [9]:
N_d1 = norm.cdf(d1)
N_d2 = norm.cdf(d2)

N_d1, N_d2

(np.float64(0.6368306511756191), np.float64(0.5596176923702425))

In [10]:
call_price = S * N_d1 - K * np.exp(-r * T) * N_d2
call_price

np.float64(10.450583572185565)

In [11]:
import sys
sys.path.append('../src')

In [12]:
from black_scholes import black_scholes_call

In [13]:
black_scholes_call(S = 100, K = 100 , sigma = 0.2, r = 0.05, T = 1)

np.float64(10.450583572185565)

In [14]:
import sys
sys.path.append('../src')
from black_scholes import black_scholes_put

In [15]:
from black_scholes import black_scholes_put
black_scholes_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(5.573526022256971)

In [16]:
import importlib
import black_scholes
importlib.reload(black_scholes)
from black_scholes import black_scholes_call, black_scholes_put

In [17]:
from black_scholes import delta_call
from black_scholes import delta_put

In [18]:
delta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(0.6368306511756191)

In [19]:
delta_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-0.3631693488243809)

In [20]:

import importlib
importlib.reload(black_scholes)

In [21]:
from black_scholes import gamma

In [22]:
gamma(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(0.018762017345846895)

In [23]:
import importlib
importlib.reload(black_scholes)
from black_scholes import vega

In [24]:
vega(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(37.52403469169379)

In [25]:
vega(S=100, K=150, r=0.05, sigma=0.2, T=1)

np.float64(9.772000145726361)

In [26]:
import importlib
importlib.reload(black_scholes)

In [27]:
from black_scholes import theta_call
theta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-6.414027546438197)

In [28]:
import importlib
importlib.reload(black_scholes)

In [29]:
from black_scholes import rho_call
rho_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(53.232481545376345)

In [30]:
from black_scholes import rho_put
rho_put(S=100, K=100, r=0.05, sigma=0.2, T=1)

np.float64(-41.89046090469506)

In [31]:
import importlib

In [32]:
importlib.reload(black_scholes)

In [33]:
from black_scholes import delta_call_numerical, delta_call

In [34]:
numerical = delta_call_numerical(S=100, K=100, r=0.05, sigma=0.2, T=1)
analytical = delta_call(S=100, K=100, r=0.05, sigma=0.2, T=1)

numerical, analytical

(np.float64(0.6368306425763137), np.float64(0.6368306511756191))

In [35]:
import importlib
importlib.reload(black_scholes)

In [36]:
from black_scholes import gamma_numerical
gamma_numerical(S=100, K=100, r=0.05, sigma=0.2, T=1, h=0.0001)

np.float64(0.018761880937745445)

In [37]:
import sys, os
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))

In [38]:
from binomial import binomial_price
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=3, q=0)

np.float64(11.043871091951113)

In [39]:
from binomial import binomial_price
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=2, q=0, option_type='call', american=False)

np.float64(9.540501338582947)

In [40]:
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=100, q=0, option_type='call', american=False)

np.float64(10.430611662249113)

In [41]:
binomial_price(S=100, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='call', american=False)

np.float64(10.44658513644654)

In [42]:
import importlib
importlib.reload(black_scholes)

In [43]:
# American put, deep in-the-money — early exercise should add real value here
binomial_price(S=80, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='put', american=True)

np.float64(20.0)

In [44]:
binomial_price(S=80, K=100, r=0.05, sigma=0.2, T=1, N=500, q=0, option_type='put', american=False)

np.float64(16.983137118259393)

In [45]:
from monte_carlo import monte_carlo_call
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=5, seed=42)

np.float64(13.522454507401847)

In [46]:
from monte_carlo import monte_carlo_call
# restart kernel first

monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=5, seed=42)

np.float64(13.522454507401847)

In [47]:
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=100000, seed=42)

np.float64(10.47389196070258)

In [48]:
monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=1000000, seed=42)

np.float64(10.434157688982824)

In [49]:
# Run 100,000 sims five separate times (no fixed seed) — watch how much they vary
[monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=1000000) for _ in range(5)]

[np.float64(10.459202124096821),
 np.float64(10.452150509799127),
 np.float64(10.450558888427537),
 np.float64(10.456686428080205),
 np.float64(10.438973533748085)]

In [50]:
from monte_carlo import monte_carlo_call, monte_carlo_call_antithetic
# restart kernel first

[monte_carlo_call_antithetic(S=100, K=100, r=0.05, sigma=0.2, T=1, q=0, n_simulations=1000000, seed=42) for _ in range(5)]

[np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086),
 np.float64(10.456798188927086)]

In [51]:
# Plain Monte Carlo — 5 runs, small n_simulations to make spread visible
[monte_carlo_call(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000) for _ in range(5)]

[np.float64(10.367033313398208),
 np.float64(10.610462259003915),
 np.float64(10.309140256582728),
 np.float64(10.380410291111975),
 np.float64(10.55075981829986)]

In [52]:
# Antithetic — same n_simulations, 5 runs
[monte_carlo_call_antithetic(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000) for _ in range(5)]

[np.float64(10.6240416300026),
 np.float64(10.546187221169946),
 np.float64(10.450979180137036),
 np.float64(10.479650982262912),
 np.float64(10.480538365483373)]

In [53]:
from monte_carlo import monte_carlo_call_control_variate
[monte_carlo_call_control_variate(S=100, K=100, r=0.05, sigma=0.2, T=1, n_simulations=10000)for _ in range(5)]

[np.float64(10.451839876232127),
 np.float64(10.45647104530929),
 np.float64(10.448927776987459),
 np.float64(10.454923225108473),
 np.float64(10.417638670537002)]

In [54]:
import yfinance as yf
reliance = yf.Ticker("RELIANCE.NS")
reliance.info

{'address1': 'Maker Chambers IV',
 'address2': '3rd Floor 222 Nariman Point',
 'city': 'Mumbai',
 'zip': '400021',
 'country': 'India',
 'phone': '91 22 3555 5000',
 'fax': '91 22 2204 2268',
 'website': 'https://www.ril.com',
 'industry': 'Oil & Gas Refining & Marketing',
 'industryKey': 'oil-gas-refining-marketing',
 'industryDisp': 'Oil & Gas Refining & Marketing',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Reliance Industries Limited engages in hydrocarbon exploration and production, petroleum refining and marketing, petrochemicals, advanced materials and composites, renewable, financial services, retail, and digital services worldwide. It operates through the Oil to Chemicals, Oil and Gas, Retail, Digital Services, and Others segments. The company is involved in refining and marketing products, including liquefied petroleum gas, propylene, naphtha, gasoline, jet/aviation turbine fuel, kerosine oil, diesel, sulfur, and petroleum coke. It also provides polymers comprising high-density and low-density polyethylene (PE), linear low-density PE, homopolymer, random and impact copolymer, and polyvinyl chloride; fiber intermediates that include purified terephthalic acid, and ethylene glycols and oxide; aromatics, such as paraxylene, ortho xylene, benzene, and linear alkyl benzene and paraffin; and textiles that consist of fabrics, apparel, and auto furnishings. In addition, the company offers elastomers, such as polybutadiene rubber, styrene butadiene rubber, and butyl rubber; fiber and yarn polyesters; and bioenergy solutions, including compressed biogas, and pellets and briquettes. Further, it engages in oil and gas exploration and production activities; operation of various stores comprising supermarkets, hypermarket, wholesale cash and carry, specialty, and online stores; operation of media and entertainment platforms, and Network18 and television channels; and publishing of magazines. Additionally, the company provides highway hospitality and fleet management services, as well as digital services, such as connectivity, fiber, mobile devices, apps, business, and other digital solutions. Reliance Industries Limited was founded in 1957 and is based in Mumbai, India.',
 'fullTimeEmployees': 404501,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Mukesh Dhirubhai Ambani',
   'age': 68,
   'title': 'Chairman & MD',
   'yearBorn': 1957,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nikhil Rasiklal Meswani',
   'age': 59,
   'title': 'Executive Director',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hital Rasiklal Meswani',
   'age': 57,
   'title': 'Executive Director',
   'yearBorn': 1968,
   'fiscalYear': 2026,
   'totalPay': 250000000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Panda Madhusudana Siva Prasad',
   'age': 73,
   'title': 'Executive Director',
   'yearBorn': 1952,
   'fiscalYear': 2026,
   'totalPay': 205800000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anant Mukesh Ambani',
   'age': 30,
   'title': 'Whole-Time Director',
   'yearBorn': 1995,
   'fiscalYear': 2026,
   'totalPay': 123900000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Parul  Sharma',
   'title': 'Group President',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Srikanth  Venkatachari',
   'age': 59,
   'title': 'Chief Financial Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Mahesh  Marve',
   'title': 'Head of Research & Technology',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hemen Kanu Modi',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Savithri  Parekh',
   'age': 59,
   'title': 'Company Secretary & Compliance Officer',
   'yearBorn': 1966,
   'fiscalYear': 2026,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 9,
 'compensationRisk': 6,
 'shareHolderRightsRisk': 1,
 'overallRisk': 10,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1798675200,
 'irWebsite': 'http://ril.com/html/investor/investor.html',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1287.0,
 'open': 1278.7,
 'dayLow': 1271.0,
 'dayHigh': 1287.0,
 'regularMarketPreviousClose': 1287.0,
 'regularMarketOpen': 1278.7,
 'regularMarketDayLow': 1271.0,
 'regularMarketDayHigh': 1287.0,
 'dividendRate': 6.0,
 'dividendYield': 0.47,
 'exDividendDate': 1780617600,
 'payoutRatio': 0.2083,
 'fiveYearAvgDividendYield': 0.44,
 'beta': 0.157,
 'trailingPE': 23.238544,
 'forwardPE': 17.95298,
 'volume': 4463073,
 'regularMarketVolume': 4464146,
 'averageVolume': 12831951,
 'averageVolume10days': 8027361,
 'averageDailyVolume10Day': 8027361,
 'bid': 1282.8,
 'ask': 1282.9,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 17362162024448,
 'nonDilutedMarketCap': 17351336411314,
 'fiftyTwoWeekLow': 1249.8,
 'fiftyTwoWeekHigh': 1611.8,
 'allTimeHigh': 1611.8,
 'allTimeLow': 5.428648,
 'fulldayPrice': 1283.0,
 'priceToSalesTrailing12Months': 1.5370117,
 'fiftyDayAverage': 1304.352,
 'twoHundredDayAverage': 1388.9225,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'INR',
 'tradeable': False,
 'enterpriseValue': 20633182273536,
 'profitMargins': 0.066149995,
 'floatShares': 6638895750,
 'sharesOutstanding': 13532472634,
 'heldPercentInsiders': 0.51798,
 'heldPercentInstitutions': 0.28070998,
 'impliedSharesOutstanding': 13532472635,
 'bookValue': 668.045,
 'priceToBook': 1.9205294,
 'lastFiscalYearEnd': 1774915200,
 'nextFiscalYearEnd': 1806451200,
 'mostRecentQuarter': 1782777600,
 'earningsQuarterlyGrowth': -0.224,
 'netIncomeToCommon': 747269980160,
 'trailingEps': 55.21,
 'forwardEps': 71.46446,
 'pegRatio': 0.82,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1730073600,
 'enterpriseToRevenue': 1.827,
 'enterpriseToEbitda': 11.423,
 '52WeekChange': -0.049412787,
 'SandP52WeekChange': 0.20204377,
 'lastDividendValue': 6.0,
 'lastDividendDate': 1780617600,
 'quoteType': 'EQUITY',
 'currentPrice': 1283.0,
 'targetHighPrice': 1890.0,
 'targetLowPrice': 1350.0,
 'targetMeanPrice': 1677.8889,
 'targetMedianPrice': 1690.0,
 'recommendationMean': 1.30769,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 27,
 'totalCash': 2581470117888,
 'totalCashPerShare': 190.761,
 'ebitda': 1806359986176,
 'totalDebt': 3979999969280,
 'totalRevenue': 11296050249728,
 'debtToEquity': 36.653,
 'revenuePerShare': 834.734,
 'grossProfits': 3822279983104,
 'earningsGrowth': -0.224,
 'revenueGrowth': 0.297,
 'grossMargins': 0.33837003,
 'ebitdaMargins': 0.15991001,
 'operatingMargins': 0.12331,
 'financialCurrency': 'INR',
 'symbol': 'RELIANCE.NS',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Free Realtime Quote',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'corporateActions': [],
 'regularMarketTime': 1788158824,
 'exchange': 'NSI',
 'messageBoardId': 'finmb_878373',
 'exchangeTimezoneName': 'Asia/Kolkata',
 'exchangeTimezoneShortName': 'IST',
 'gmtOffSetMilliseconds': 19800000,
 'market': 'in_market',
 'esgPopulated': False,
 'marketState': 'REGULAR',
 'regularMarketChange': -4.0,
 'fulldayChange': -4.0,
 'fulldayChangePercent': -0.3108003,
 'regularMarketDayRange': '1271.0 - 1287.0',
 'fullExchangeName': 'NSE',
 'averageDailyVolume3Month': 12831951,
 'fiftyTwoWeekLowChange': 33.19995,
 'fiftyTwoWeekLowChangePercent': 0.02656421,
 'fiftyTwoWeekRange': '1249.8 - 1611.8',
 'fiftyTwoWeekHighChange': -328.80005,
 'fiftyTwoWeekHighChangePercent': -0.20399556,
 'fiftyTwoWeekChangePercent': -4.9412785,
 'earningsTimestamp': 1784282400,
 'earningsTimestampStart': 1792144800,
 'earningsTimestampEnd': 1792144800,
 'earningsCallTimestampStart': 1745592300,
 'earningsCallTimestampEnd': 1745592300,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 55.21,
 'epsForward': 71.46446,
 'epsCurrentYear': 64.0101,
 'regularMarketChangePercent': -0.3108003,
 'regularMarketPrice': 1283.0,
 'priceEpsCurrentYear': 20.04371,
 'fiftyDayAverageChange': -21.35205,
 'fiftyDayAverageChangePercent': -0.016369853,
 'twoHundredDayAverageChange': -105.922485,
 'twoHundredDayAverageChangePercent': -0.07626235,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 15,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 820467900000,
 'shortName': 'RELIANCE INDUSTRIES LTD',
 'longName': 'Reliance Industries Limited',
 'trailingPegRatio': None}

In [55]:
reliance = yf.Ticker("RELIANCE.NS")
price = reliance.info['currentPrice']
price

1283.0

In [56]:
history = reliance.history(period="1d")
history

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-08-31 00:00:00+05:30,1278.699951,1287.0,1271.0,1283.0,4464146,0.0,0.0

In [57]:
latest_price = history['Close'].iloc[-1]
latest_price

np.float64(1283.0)

In [58]:
history = reliance.history(period = "1d")
latest_price = history['Close'].iloc[-1]
latest_price

np.float64(1283.0)

In [59]:
from market_data import get_spot_price
get_spot_price("RELIANCE.NS")

1283.0

In [60]:
get_spot_price("SILVERBEES.NS")

222.89999389648438

In [61]:
get_spot_price("AAPL")

319.70001220703125

In [62]:
reliance = yf.Ticker("RELIANCE.NS")
expiries = reliance.options
expiries

()

In [63]:
nifty = yf.Ticker("^NSEI")
nifty.options

()

In [64]:
tcs = yf.Ticker("TCS.NS")
tcs.options

()

In [65]:
aapl = yf.Ticker("AAPL")
expiries = aapl.options
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-09',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-09',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [66]:
chain = aapl.option_chain(expiries[0])
chain.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:43+00:00,225.0,95.54,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
1,AAPL260831C00230000,2026-08-28 14:21:14+00:00,230.0,86.63,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
2,AAPL260831C00235000,2026-08-17 18:05:20+00:00,235.0,68.01,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
3,AAPL260831C00240000,2026-08-17 18:05:20+00:00,240.0,63.00,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
4,AAPL260831C00250000,2026-08-20 14:33:30+00:00,250.0,66.80,0.0,0.0,0.0,0.0,NaN,0.0,0.000010,True,REGULAR,USD
5,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,0.0,0.0,0.0,0.0,1.0,0.0,0.000010,True,REGULAR,USD
6,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
7,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,0.0,0.0,0.0,0.0,7.0,0.0,0.000010,True,REGULAR,USD
8,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,0.0,0.0,0.0,0.0,7.0,0.0,0.000010,True,REGULAR,USD
9,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,0.0,0.0,0.0,0.0,4.0,0.0,0.000010,True,REGULAR,USD
10,AAPL260831C00290000,2026-08-28 14:14:28+00:00,290.0,26.38,0.0,0.0,0.0,0.0,2.0,0.0,0.000010,True,REGULAR,USD
11,AAPL260831C00292500,2026-08-25 19:52:33+00:00,292.5,17.15,0.0,0.0,0.0,0.0,213.0,0.0,0.000010,True,REGULAR,USD
12,AAPL260831C00295000,2026-08-28 19:47:08+00:00,295.0,25.07,0.0,0.0,0.0,0.0,110.0,0.0,0.000010,True,REGULAR,USD
13,AAPL260831C00297500,2026-08-28 16:02:06+00:00,297.5,23.78,0.0,0.0,0.0,0.0,10.0,0.0,0.000010,True,REGULAR,USD
14,AAPL260831C00300000,2026-08-28 18:14:24+00:00,300.0,19.84,0.0,0.0,0.0,0.0,6.0,0.0,0.000010,True,REGULAR,USD
15,AAPL260831C00302500,2026-08-28 13:46:02+00:00,302.5,13.65,0.0,0.0,0.0,0.0,4.0,0.0,0.000010,True,REGULAR,USD
16,AAPL260831C00305000,2026-08-28 19:35:13+00:00,305.0,15.08,0.0,0.0,0.0,0.0,10.0,0.0,0.000010,True,REGULAR,USD
17,AAPL260831C00307500,2026-08-28 19:59:51+00:00,307.5,10.95,0.0,0.0,0.0,0.0,71.0,0.0,0.000010,True,REGULAR,USD
18,AAPL260831C00310000,2026-08-28 19:53:16+00:00,310.0,10.00,0.0,0.0,0.0,0.0,481.0,0.0,0.000010,True,REGULAR,USD
19,AAPL260831C00312500,2026-08-28 19:57:34+00:00,312.5,7.65,0.0,0.0,0.0,0.0,567.0,0.0,0.000010,True,REGULAR,USD
20,AAPL260831C00315000,2026-08-28 19:58:41+00:00,315.0,5.25,0.0,0.0,0.0,0.0,6777.0,0.0,0.000010,True,REGULAR,USD
21,AAPL260831C00317500,2026-08-28 19:59:32+00:00,317.5,3.05,0.0,0.0,0.0,0.0,14265.0,0.0,0.000010,True,REGULAR,USD
22,AAPL260831C00320000,2026-08-28 19:59:58+00:00,320.0,1.40,0.0,0.0,0.0,0.0,32256.0,0.0,0.007822,False,REGULAR,USD
23,AAPL260831C00322500,2026-08-28 19:59:55+00:00,322.5,0.69,0.0,0.0,0.0,0.0,25298.0,0.0,0.031260,False,REGULAR,USD
24,AAPL260831C00325000,2026-08-28 19:59:58+00:00,325.0,0.27,0.0,0.0,0.0,0.0,21611.0,0.0,0.062509,False,REGULAR,USD
25,AAPL260831C00327500,2026-08-28 19:59:54+00:00,327.5,0.13,0.0,0.0,0.0,0.0,5805.0,0.0,0.125009,False,REGULAR,USD
26,AAPL260831C00330000,2026-08-28 19:59:40+00:00,330.0,0.08,0.0,0.0,0.0,0.0,7447.0,0.0,0.125009,False,REGULAR,USD
27,AAPL260831C00332500,2026-08-28 19:59:27+00:00,332.5,0.05,0.0,0.0,0.0,0.0,833.0,0.0,0.125009,False,REGULAR,USD
28,AAPL260831C00335000,2026-08-28 19:59:05+00:00,335.0,0.03,0.0,0.0,0.0,0.0,479.0,0.0,0.250007,False,REGULAR,USD
29,AAPL260831C00337500,2026-08-28 19:31:25+00:00,337.5,0.02,0.0,0.0,0.0,0.0,856.0,0.0,0.250007,False,REGULAR,USD
30,AAPL260831C00340000,2026-08-28 19:40:08+00:00,340.0,0.03,0.0,0.0,0.0,0.0,88.0,0.0,0.250007,False,REGULAR,USD
31,AAPL260831C00342500,2026-08-28 17:31:44+00:00,342.5,0.01,0.0,0.0,0.0,0.0,8.0,0.0,0.250007,False,REGULAR,USD
32,AAPL260831C00345000,2026-08-28 16:34:49+00:00,345.0,0.03,0.0,0.0,0.0,0.0,74.0,0.0,0.250007,False,REGULAR,USD
33,AAPL260831C00347500,2026-08-28 16:27:58+00:00,347.5,0.02,NaN,0.0,0.0,0.0,NaN,0.0,0.250007,False,REGULAR,USD
34,AAPL260831C00350000,2026-08-28 18:09:22+00:00,350.0,0.01,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
35,AAPL260831C00355000,2026-08-26 19:14:51+00:00,355.0,0.01,0.0,0.0,0.0,0.0,76.0,0.0,0.500005,False,REGULAR,USD
36,AAPL260831C00360000,2026-08-27 16:41:21+00:00,360.0,0.01,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
37,AAPL260831C00365000,2026-08-21 18:59:47+00:00,365.0,0.07,0.0,0.0,0.0,0.0,6.0,0.0,0.500005,False,REGULAR,USD
38,AAPL260831C00370000,2026-08-21 19:00:54+00:00,370.0,0.07,0.0,0.0,0.0,0.0,26.0,0.0,0.500005,False,REGULAR,USD
39,AAPL260831C00375000,2026-08-25 14:43:57+00:00,375.0,0.02,0.0,0.0,0.0,0.0,2.0,0.0,0.500005,False,REGULAR,USD
40,AAPL260831C00380000,2026-08-28 14:45:09+00:00,380.0,0.01,0.0,0.0,0.0,0.0,3.0,0.0,0.500005,False,REGULAR,USD
41,AAPL260831C00385000,2026-08-28 15:58:14+00:00,385.0,0.01,0.0,0.0,0.0,0.0,1.0,0.0,0.500005,False,REGULAR,USD
42,AAPL260831C00390000,2026-08-26 16:34:00+00:00,390.0,0.01,NaN,0.0,0.0,0.0,NaN,0.0,0.500005,False,REGULAR,USD
43,AAPL260831C00405000,2026-08-28 13:30:10+00:00,405.0,0.01,NaN,0.0,0.0,0.0,NaN,NaN,0.500005,False,REGULAR,USD

In [67]:
from market_data import get_spot_price
get_spot_price("AAPL")

319.70001220703125

In [68]:
chain.calls.shape

(44, 14)

In [69]:
chain.calls.columns

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice', 'bid', 'ask',
       'change', 'percentChange', 'volume', 'openInterest',
       'impliedVolatility', 'inTheMoney', 'contractSize', 'currency'],
      dtype='str')

In [70]:
chain.calls.head(10)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260831C00225000,2026-08-28 15:11:43+00:00,225.0,95.54,0.0,0.0,0.0,0.0,2.0,0.0,0.00001,True,REGULAR,USD
1,AAPL260831C00230000,2026-08-28 14:21:14+00:00,230.0,86.63,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
2,AAPL260831C00235000,2026-08-17 18:05:20+00:00,235.0,68.01,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
3,AAPL260831C00240000,2026-08-17 18:05:20+00:00,240.0,63.00,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
4,AAPL260831C00250000,2026-08-20 14:33:30+00:00,250.0,66.80,0.0,0.0,0.0,0.0,NaN,0.0,0.00001,True,REGULAR,USD
5,AAPL260831C00275000,2026-08-24 17:37:23+00:00,275.0,37.30,0.0,0.0,0.0,0.0,1.0,0.0,0.00001,True,REGULAR,USD
6,AAPL260831C00280000,2026-08-28 19:12:26+00:00,280.0,39.52,0.0,0.0,0.0,0.0,2.0,0.0,0.00001,True,REGULAR,USD
7,AAPL260831C00282500,2026-08-28 19:39:41+00:00,282.5,37.05,0.0,0.0,0.0,0.0,7.0,0.0,0.00001,True,REGULAR,USD
8,AAPL260831C00285000,2026-08-28 19:41:13+00:00,285.0,34.61,0.0,0.0,0.0,0.0,7.0,0.0,0.00001,True,REGULAR,USD
9,AAPL260831C00287500,2026-08-28 19:41:13+00:00,287.5,32.13,0.0,0.0,0.0,0.0,4.0,0.0,0.00001,True,REGULAR,USD

In [71]:
import importlib
import market_data

importlib.reload(market_data)

In [72]:
from market_data import filter_liquid_options

liquid_calls = filter_liquid_options(chain.calls)
liquid_calls

Empty DataFrame
Columns: [contractSymbol, lastTradeDate, strike, lastPrice, bid, ask, change, percentChange, volume, openInterest, impliedVolatility, inTheMoney, contractSize, currency]
Index: []

In [73]:
liquid_calls.shape

(0, 14)

In [74]:
liquid_calls[['strike', 'volume', 'openInterest', 'impliedVolatility', 'bid', 'ask']].head(10)

Empty DataFrame
Columns: [strike, volume, openInterest, impliedVolatility, bid, ask]
Index: []

In [75]:
from datetime import datetime

expiry_date = datetime.strptime(expiries[0], '%Y-%m-%d')
today = datetime.now()

days_to_expiry = (expiry_date - today).days
T = days_to_expiry / 365

T

-0.0027397260273972603

In [76]:
S = get_spot_price("AAPL")
K = 280.0
sigma = 0.500005

In [77]:
from black_scholes import black_scholes_call
from binomial import binomial_price
from monte_carlo import monte_carlo_call

bs_price = black_scholes_call(S=S, K=K,sigma=sigma, r = 0.05, T=T)
bs_price

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\black_scholes.py:21: RuntimeWarning: invalid value encountered in sqrt
  d1 = (np.log(S / K) + (r - q + sigma**2 / 2) * T) / (sigma * np.sqrt(T))
c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\black_scholes.py:22: RuntimeWarning: invalid value encountered in sqrt
  d2 = d1 - sigma * np.sqrt(T)

np.float64(nan)

In [78]:
binomial_price_val = binomial_price(S=S, K=K, r=0.05, sigma=sigma, T=T, N=500, option_type='call', american=True)
binomial_price_val

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\binomial.py:25: RuntimeWarning: invalid value encountered in sqrt
  u = np.exp(sigma * np.sqrt(dt))

np.float64(nan)

In [79]:
mc_price = monte_carlo_call(S=S, K=K, r=0.05, sigma=sigma, T=T, n_simulations=100000, seed=42)
mc_price

c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\monte_carlo.py:27: RuntimeWarning: invalid value encountered in sqrt
  S_T = S * np.exp((r - q - sigma**2 / 2) * T + sigma * np.sqrt(T) * Z)

np.float64(nan)

In [80]:
T

-0.0027397260273972603

In [81]:
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-09',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-09',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [82]:
chosen_expiry = expiries[7]
chosen_expiry

'2026-10-02'

In [83]:
chain = aapl.option_chain(chosen_expiry)
liquid_calls = filter_liquid_options(chain.calls)
liquid_calls[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

Empty DataFrame
Columns: [strike, bid, ask, volume, openInterest, impliedVolatility]
Index: []

In [84]:
from datetime import datetime

expiry_date = datetime.strptime(chosen_expiry, '%Y-%m-%d')
today = datetime.now()

days_to_expiry = (expiry_date - today).days
T = days_to_expiry / 365

T

0.08493150684931507

In [85]:
S = get_spot_price("AAPL")
S

319.70001220703125

In [86]:
liquid_calls['distance_from_spot'] = abs(liquid_calls['strike'] - S)
liquid_calls.sort_values('distance_from_spot')[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

Empty DataFrame
Columns: [strike, bid, ask, volume, openInterest, impliedVolatility]
Index: []

In [87]:
K = 320.0
sigma = 0.266945
bid = 11.75
ask = 12.20

In [88]:
from black_scholes import black_scholes_call
from binomial import binomial_price
from monte_carlo import monte_carlo_call

In [89]:
r = 0.05  # placeholder risk-free rate

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T)
binomial_price_val = binomial_price(S=S, K=K, r=r, sigma=sigma, T=T, N=500, option_type='call', american=True)
mc_price = monte_carlo_call(S=S, K=K, r=r, sigma=sigma, T=T, n_simulations=100000, seed=42)

bs_price, binomial_price_val, mc_price

(np.float64(10.440304969338996),
 np.float64(10.439958174848861),
 np.float64(10.464902023325722))

In [90]:
q = 0.0034

bs_price_with_div = black_scholes_call(S=S, K=K, r=0.05, sigma=sigma, T=T, q=q)
binomial_price_with_div = binomial_price(S=S, K=K, r=0.05, sigma=sigma, T=T, N=500, q=q, option_type='call', american=True)
mc_price_with_div = monte_carlo_call(S=S, K=K, r=0.05, sigma=sigma, T=T, q=q, n_simulations=100000, seed=42)

bs_price_with_div, binomial_price_with_div, mc_price_with_div

(np.float64(10.391225081813303),
 np.float64(10.390879995203205),
 np.float64(10.415720953209492))

In [91]:
expiries

('2026-08-31',
 '2026-09-02',
 '2026-09-04',
 '2026-09-09',
 '2026-09-11',
 '2026-09-18',
 '2026-09-25',
 '2026-10-02',
 '2026-10-09',
 '2026-10-16',
 '2026-11-20',
 '2026-12-18',
 '2027-01-15',
 '2027-02-19',
 '2027-03-19',
 '2027-04-16',
 '2027-06-17',
 '2027-09-17',
 '2027-12-17',
 '2028-01-21',
 '2028-03-17',
 '2028-12-15')

In [92]:
from market_data import get_risk_free_rate
get_risk_free_rate()

0.037300000190734865

In [93]:
import importlib
import market_data

importlib.reload(market_data)

In [94]:
get_risk_free_rate

In [95]:
get_risk_free_rate()

0.037300000190734865

In [96]:
importlib.reload(market_data)

In [97]:
from market_data import get_risk_free_rate
get_risk_free_rate()

0.037300000190734865

In [98]:
import tests.test_real_data_validation

ModuleNotFoundError: No module named 'tests'

In [ ]:
from tests import test_real_data_validation

ModuleNotFoundError: No module named 'tests'

In [ ]:
import importlib
import market_data
importlib.reload(market_data)

In [ ]:
from market_data import get_liquid_near_the_money_contract

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')  # or however you fetched this earlier
r = get_risk_free_rate()
q = 0.0034

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
bs_price

np.float64(8.916706502638277)

In [ ]:
importlib.reload(market_data)

In [ ]:
from market_data import get_liquid_near_the_money_contract, get_risk_free_rate

S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')
r = get_risk_free_rate()
q = 0.0034

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
bs_price

np.float64(8.916706502638277)

In [ ]:
S, K, sigma, T, r

(319.70001220703125,
 320.0,
 0.260749580078125,
 0.0684931506849315,
 0.037300000190734865)

In [ ]:
liquid_calls[['strike', 'bid', 'ask']]  # or re-fetch if this variable isn't still in scope

    strike     bid     ask
0    130.0  188.55  192.30
1    135.0  183.45  187.35
2    140.0  178.50  182.35
3    145.0  173.55  177.40
4    150.0  168.55  172.45
..     ...     ...     ...
74   560.0    0.00    1.03
75   570.0    0.00    1.03
76   580.0    0.00    1.03
77   590.0    0.00    0.01
78   600.0    0.00    0.01

[79 rows x 3 columns]

In [ ]:
r

0.037300000190734865

In [ ]:
from datetime import datetime

# rebuild the same expiry that get_liquid_near_the_money_contract picked
aapl = yf.Ticker("AAPL")
expiries = aapl.options
for expiry in expiries:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    if days_out >= 20:
        chosen_expiry = expiry
        break

chain = aapl.option_chain(chosen_expiry)
chain.calls[chain.calls['strike'] == 320.0][['strike', 'bid', 'ask', 'volume', 'openInterest']]

    strike   bid  ask  volume  openInterest
26   320.0  8.55  8.9   895.0          1621

In [ ]:
from market_data import get_historical_volatality

ImportError: cannot import name 'get_historical_volatality' from 'market_data' (c:\Ansh\Quant Projects\Derivatives-Pricing-Engine\notebooks\../src\market_data.py)

In [ ]:
importlib.reload(market_data)

In [ ]:
from market_data import get_historical_volatality

In [ ]:
importlib.reload(market_data)

In [ ]:
from market_data import get_historical_volatility

In [ ]:
from market_data import get_historical_volatility
# restart kernel first

hist_vol = get_historical_volatility("AAPL")
hist_vol

0.3274446531289782

In [ ]:
from market_data import get_liquid_near_the_money_contract

In [ ]:
S, K, sigma_implied, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')

hist_vol, sigma_implied

(0.3274446531289782, 0.260749580078125)

In [ ]:
from black_scholes import black_scholes_call

r = get_risk_free_rate()
q = 0.0034

price_with_implied_vol = black_scholes_call(S=S, K=K, r=r, sigma=sigma_implied, T=T, q=q)
price_with_historical_vol = black_scholes_call(S=S, K=K, r=r, sigma=hist_vol, T=T, q=q)

price_with_implied_vol, price_with_historical_vol

(np.float64(8.916706502638277), np.float64(11.138861063506084))

In [ ]:
import black_scholes

In [ ]:
import dashboard
import importlib
importlib.reload(dashboard)

In [ ]:
from dashboard import build_greeks_dashboard
# restart kernel first

S, r, T, chosen_expiry, liquid_contracts = build_greeks_dashboard("AAPL", option_side='calls')

S, r, T, chosen_expiry

ValueError: No sufficiently liquid calls found for 'AAPL'.

In [ ]:
import yfinance as yf
from datetime import datetime

ticker = yf.Ticker("AAPL")
expiries = ticker.options

for expiry in expiries:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    print(expiry, days_out)

2026-08-31 -1
2026-09-02 1
2026-09-04 3
2026-09-09 8
2026-09-11 10
2026-09-18 17
2026-09-25 24
2026-10-02 31
2026-10-09 38
2026-10-16 45
2026-11-20 80
2026-12-18 108
2027-01-15 136
2027-02-19 171
2027-03-19 199
2027-04-16 227
2027-06-17 289
2027-09-17 381
2027-12-17 472
2028-01-21 507
2028-03-17 563
2028-12-15 836

In [ ]:
chosen_expiry = expiries[7]  # whichever one matched >= 20 days from the printout
chain = ticker.option_chain(chosen_expiry)
chain.calls[['strike', 'volume', 'openInterest']].describe()

           strike       volume  openInterest
count   37.000000    36.000000          37.0
mean   323.378378   176.222222           0.0
std     57.167566   581.464167           0.0
min    195.000000     1.000000           0.0
25%    280.000000     2.000000           0.0
50%    325.000000    12.000000           0.0
75%    370.000000    99.250000           0.0
max    415.000000  3475.000000           0.0

In [ ]:
from market_data import filter_liquid_options

test_filtered = filter_liquid_options(chain.calls, min_volume=1, min_open_interest=1)
len(test_filtered)

0

In [ ]:
from market_data import get_liquid_near_the_money_contract

S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='puts')
S, K, sigma, T

(319.70001220703125, 320.0, 1.0000000000000003e-05, 0.06575342465753424)

In [ ]:
from dashboard import build_greeks_dashboard
# restart kernel first

S, r, T, chosen_expiry, liquid_contracts = build_greeks_dashboard("AAPL", option_side='calls')

S, r, T, chosen_expiry

(319.70001220703125, 0.037300000190734865, 0.06575342465753424, '2026-09-25')

In [ ]:
liquid_contracts[['strike', 'bid', 'ask', 'impliedVolatility']]

    strike  bid  ask  impliedVolatility
28   325.0  0.0  0.0           0.015635
29   330.0  0.0  0.0           0.031260
30   335.0  0.0  0.0           0.031260
31   340.0  0.0  0.0           0.062509
32   345.0  0.0  0.0           0.062509
33   350.0  0.0  0.0           0.062509
34   355.0  0.0  0.0           0.062509
35   360.0  0.0  0.0           0.125009
36   365.0  0.0  0.0           0.125009
37   370.0  0.0  0.0           0.125009
43   400.0  0.0  0.0           0.125009

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')
S, K, sigma, T

NameError: name 'get_liquid_near_the_money_contract' is not defined

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')
S, K, sigma, T

NameError: name 'get_liquid_near_the_money_contract' is not defined

In [ ]:
from market_data import get_liquid_near_the_money_contract

ModuleNotFoundError: No module named 'market_data'

In [ ]:
from market_data import get_liquid_near_the_money_contract

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='calls')
S, K, sigma, T

(319.70001220703125, 95.0, 1.1616252856445315, 0.2958904109589041)

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("AAPL", option_side='puts')
S, K, T

(319.70001220703125, 385.0, 0.3726027397260274)

In [ ]:
from market_data import get_spot_price, filter_liquid_options
from datetime import datetime
import yfinance as yf

In [ ]:
S = get_spot_price("AAPL")
aapl = yf.Ticker("AAPL")

for expiry in aapl.options:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    if days_out < 20:
        continue
    chain = aapl.option_chain(expiry)
    liquid = filter_liquid_options(chain.calls, min_volume=1, min_open_interest=1)
    if len(liquid) == 0:
        print(expiry, "no liquid calls at all")
        continue
    liquid = liquid.copy()
    liquid['dist'] = abs(liquid['strike'] - S)
    closest = liquid['dist'].min()
    print(expiry, f"closest liquid strike is {closest:.1f} away (limit is {S*0.15:.1f})")

2026-09-25 no liquid calls at all
2026-10-02 no liquid calls at all
2026-10-09 no liquid calls at all
2026-10-16 no liquid calls at all
2026-11-20 closest liquid strike is 209.7 away (limit is 48.0)
2026-12-18 closest liquid strike is 224.7 away (limit is 48.0)
2027-01-15 closest liquid strike is 249.7 away (limit is 48.0)
2027-02-19 closest liquid strike is 204.7 away (limit is 48.0)
2027-03-19 closest liquid strike is 174.7 away (limit is 48.0)
2027-04-16 no liquid calls at all
2027-06-17 no liquid calls at all
2027-09-17 closest liquid strike is 139.7 away (limit is 48.0)
2027-12-17 no liquid calls at all
2028-01-21 no liquid calls at all
2028-03-17 closest liquid strike is 210.3 away (limit is 48.0)
2028-12-15 no liquid calls at all

In [ ]:
S = get_spot_price("AAPL")
expiry = "2026-11-20"  # pick one that showed a real result above

chain = aapl.option_chain(expiry)
near = chain.calls.copy()
near['dist'] = abs(near['strike'] - S)
near.sort_values('dist')[['strike', 'bid', 'ask', 'volume', 'openInterest', 'impliedVolatility']].head(10)

    strike  bid  ask  volume  openInterest  impliedVolatility
44   320.0  0.0  0.0  1070.0           0.0           0.000498
43   315.0  0.0  0.0   264.0           0.0           0.000010
45   325.0  0.0  0.0  1063.0           0.0           0.007822
42   310.0  0.0  0.0   315.0           0.0           0.000010
46   330.0  0.0  0.0   425.0           0.0           0.015635
41   305.0  0.0  0.0   185.0           0.0           0.000010
47   335.0  0.0  0.0   377.0           0.0           0.015635
40   300.0  0.0  0.0   226.0           0.0           0.000010
48   340.0  0.0  0.0   356.0           0.0           0.031260
39   295.0  0.0  0.0    52.0           0.0           0.000010

In [ ]:
S_spx = get_spot_price("^SPX")
S_spx

7711.759765625

In [ ]:
spx = yf.Ticker("^SPX")
spx.options

('2026-08-31',
 '2026-09-01',
 '2026-09-02',
 '2026-09-03',
 '2026-09-04',
 '2026-09-08',
 '2026-09-09',
 '2026-09-10',
 '2026-09-11',
 '2026-09-14',
 '2026-09-15',
 '2026-09-16',
 '2026-09-17',
 '2026-09-18',
 '2026-09-21',
 '2026-09-22',
 '2026-09-23',
 '2026-09-24',
 '2026-09-25',
 '2026-09-28',
 '2026-09-29',
 '2026-09-30',
 '2026-10-01',
 '2026-10-02',
 '2026-10-05',
 '2026-10-06',
 '2026-10-09',
 '2026-10-12',
 '2026-10-16',
 '2026-10-30',
 '2026-11-03',
 '2026-11-04',
 '2026-11-20',
 '2026-11-30',
 '2026-12-18',
 '2026-12-31',
 '2027-01-15',
 '2027-01-29',
 '2027-02-19',
 '2027-03-19',
 '2027-03-31',
 '2027-04-16',
 '2027-05-21',
 '2027-06-17',
 '2027-06-30',
 '2027-07-16',
 '2027-08-20',
 '2027-09-17',
 '2027-12-17',
 '2028-06-16',
 '2028-12-15',
 '2029-12-21',
 '2030-12-20',
 '2031-12-19')

In [ ]:
S_spx = get_spot_price("^SPX")

for expiry in spx.options:
    days_out = (datetime.strptime(expiry, '%Y-%m-%d') - datetime.now()).days
    if days_out < 20:
        continue
    chain = spx.option_chain(expiry)
    liquid = filter_liquid_options(chain.calls, min_volume=1, min_open_interest=1)
    if len(liquid) == 0:
        print(expiry, "no liquid calls at all")
        continue
    liquid = liquid.copy()
    liquid['dist'] = abs(liquid['strike'] - S_spx)
    closest = liquid['dist'].min()
    print(expiry, f"closest liquid strike is {closest:.1f} away (limit is {S_spx*0.15:.1f})")

2026-09-21 closest liquid strike is 1.8 away (limit is 1156.8)
2026-09-22 closest liquid strike is 1.8 away (limit is 1156.8)
2026-09-23 closest liquid strike is 1.8 away (limit is 1156.8)
2026-09-24 closest liquid strike is 8.2 away (limit is 1156.8)
2026-09-25 closest liquid strike is 1.8 away (limit is 1156.8)
2026-09-28 closest liquid strike is 11.8 away (limit is 1156.8)
2026-09-29 closest liquid strike is 11.8 away (limit is 1156.8)
2026-09-30 closest liquid strike is 1.8 away (limit is 1156.8)
2026-10-01 closest liquid strike is 8.2 away (limit is 1156.8)
2026-10-02 closest liquid strike is 1.8 away (limit is 1156.8)
2026-10-05 closest liquid strike is 11.8 away (limit is 1156.8)
2026-10-06 no liquid calls at all
2026-10-09 closest liquid strike is 438.2 away (limit is 1156.8)
2026-10-12 closest liquid strike is 388.2 away (limit is 1156.8)
2026-10-16 closest liquid strike is 1.8 away (limit is 1156.8)
2026-10-30 closest liquid strike is 1.8 away (limit is 1156.8)
2026-11-03 closest liquid strike is 13.2 away (limit is 1156.8)
2026-11-04 closest liquid strike is 11.8 away (limit is 1156.8)
2026-11-20 closest liquid strike is 1.8 away (limit is 1156.8)
2026-11-30 closest liquid strike is 1.8 away (limit is 1156.8)
2026-12-18 closest liquid strike is 11.8 away (limit is 1156.8)
2026-12-31 closest liquid strike is 1.8 away (limit is 1156.8)
2027-01-15 closest liquid strike is 11.8 away (limit is 1156.8)
2027-01-29 closest liquid strike is 1.8 away (limit is 1156.8)
2027-02-19 closest liquid strike is 11.8 away (limit is 1156.8)
2027-03-19 closest liquid strike is 11.8 away (limit is 1156.8)
2027-03-31 closest liquid strike is 1.8 away (limit is 1156.8)
2027-04-16 closest liquid strike is 11.8 away (limit is 1156.8)
2027-05-21 closest liquid strike is 11.8 away (limit is 1156.8)
2027-06-17 closest liquid strike is 11.8 away (limit is 1156.8)
2027-06-30 closest liquid strike is 11.8 away (limit is 1156.8)
2027-07-16 closest liquid strike is 11.8 away (limit is 1156.8)
2027-08-20 closest liquid strike is 11.8 away (limit is 1156.8)
2027-09-17 closest liquid strike is 11.8 away (limit is 1156.8)
2027-12-17 closest liquid strike is 11.8 away (limit is 1156.8)
2028-06-16 closest liquid strike is 11.8 away (limit is 1156.8)
2028-12-15 closest liquid strike is 11.8 away (limit is 1156.8)
2029-12-21 closest liquid strike is 11.8 away (limit is 1156.8)
2030-12-20 closest liquid strike is 888.2 away (limit is 1156.8)
2031-12-19 closest liquid strike is 1488.2 away (limit is 1156.8)

In [ ]:
S, K, sigma, T = get_liquid_near_the_money_contract("^SPX", option_side='calls')

r = get_risk_free_rate()
q = 0.013  # S&P 500 index dividend yield is different from AAPL's — worth looking up separately

bs_price = black_scholes_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q)
binom_price = binomial_price(S=S, K=K, r=r, sigma=sigma, T=T, N=500, q=q,
                              option_type='call', american=False)  # SPX is European
mc_price = monte_carlo_call(S=S, K=K, r=r, sigma=sigma, T=T, q=q,
                             n_simulations=100000, seed=42)

In [ ]:
bs_price

np.float64(80.26880093052569)

In [ ]:
binom_price

np.float64(80.30781474880934)

In [ ]:
mc_price

np.float64(80.45571015446656)

In [ ]:
r = get_risk_free_rate()
q = 0.0105  # S&P 500 index current dividend yield

In [ ]:
r

0.037300000190734865

In [ ]:
from dashboard import build_greeks_dashboard

In [ ]:
results = build_greeks_dashboard("^SPX", option_side='calls', q=0.0105)
results

,strike,market_bid,market_ask,model_price,implied_vol,delta,gamma,vega,theta_daily,rho
0,7540.0,193.90,213.70,217.87,0.1426,0.7686,0.001182,549.1074,-2.3699,312.8407
1,7610.0,151.10,152.00,155.61,0.1230,0.7004,0.001563,626.5462,-2.3077,287.4276
2,7620.0,143.70,144.60,148.03,0.1218,0.6860,0.001612,639.7252,-2.3216,281.7465
3,7640.0,129.10,130.10,133.17,0.1193,0.6556,0.001709,664.0328,-2.3375,269.7229
4,7680.0,102.40,103.30,105.62,0.1147,0.5874,0.001879,702.2646,-2.3359,242.4352
5,7700.0,90.10,91.00,92.95,0.1126,0.5501,0.001946,713.9872,-2.3115,227.3741
6,7720.0,78.60,79.50,81.09,0.1105,0.5110,0.001997,719.4604,-2.2693,211.5031
7,7725.0,76.00,76.90,78.40,0.1102,0.5010,0.002004,719.7470,-2.2592,207.4251
8,7730.0,73.20,74.20,75.62,0.1097,0.4910,0.002012,719.5775,-2.2443,203.3169
9,7740.0,68.10,69.00,70.25,0.1088,0.4706,0.002025,717.8291,-2.2118,195.0010
10,7750.0,63.10,64.00,65.09,0.1079,0.4500,0.002031,714.1406,-2.1741,186.5705
11,7760.0,58.20,59.10,60.04,0.1068,0.4290,0.002035,708.4158,-2.1284,178.0079
12,7770.0,53.60,54.50,55.29,0.1059,0.4081,0.002031,700.6467,-2.0798,169.3975
13,7775.0,51.60,52.50,53.21,0.1057,0.3978,0.002021,696.1281,-2.0594,165.1965
14,7780.0,49.40,50.30,50.95,0.1052,0.3873,0.002016,690.9430,-2.0312,160.8596
15,7790.0,45.40,46.20,46.72,0.1044,0.3664,0.001997,679.1351,-1.9748,152.2678
16,7820.0,34.60,35.30,35.48,0.1022,0.3050,0.001899,632.1622,-1.7838,126.9586
17,7825.0,33.10,33.90,34.02,0.1022,0.2958,0.001872,623.3980,-1.7564,123.1139
18,7850.0,25.70,26.50,26.42,0.1005,0.2477,0.001743,570.6877,-1.5710,103.2246
19,7875.0,19.90,20.30,20.08,0.0988,0.2030,0.001583,509.7945,-1.3723,84.6800
20,7900.0,14.90,15.60,15.28,0.0980,0.1646,0.001400,447.2907,-1.1879,68.7113
21,7925.0,11.10,11.80,11.43,0.0973,0.1310,0.001210,383.7496,-1.0066,54.7106
22,7950.0,8.20,8.80,8.42,0.0967,0.1023,0.001022,322.1042,-0.8357,42.7768
23,7975.0,6.10,6.60,6.22,0.0966,0.0795,0.000849,267.1343,-0.6896,33.2645
24,8050.0,2.45,2.85,2.56,0.0982,0.0365,0.000452,144.4902,-0.3752,15.3013
25,8075.0,1.90,2.25,1.99,0.0997,0.0289,0.000366,118.9699,-0.3127,12.0914
26,8100.0,1.45,1.80,1.56,0.1014,0.0230,0.000298,98.4010,-0.2624,9.6386
27,8125.0,1.15,1.45,1.24,0.1032,0.0184,0.000242,81.4494,-0.2205,7.7111
28,8400.0,0.20,0.40,0.30,0.1344,0.0040,0.000048,21.2284,-0.0735,1.6603
29,8600.0,0.05,0.00,0.00,0.0625,0.0000,0.000000,0.0000,-0.0000,0.0000

In [ ]:
from dashboard import  build_greeks_dashboard

In [ ]:
S, results = build_greeks_dashboard("^SPX", option_side='calls', q=0.0105)
print(f"Spot price: {S:.2f}")
results

NameError: name 'build_greeks_dashboard' is not defined

In [ ]:
from dashboard import build_greeks_dashboard

S, results = build_greeks_dashboard("^SPX", option_side='calls', q=0.0105)
print(f"Spot price: {S:.2f}")
results

ModuleNotFoundError: No module named 'dashboard'

In [99]:
from dashboard import build_greeks_dashboard

S, results = build_greeks_dashboard("^SPX", option_side='calls', q=0.0105)
print(f"Spot price: {S:.2f}")
results

Spot price: 7711.76

,strike,market_bid,market_ask,model_price,implied_vol,delta,gamma,vega,theta_daily,rho
0,7540.0,193.90,213.70,217.87,0.1426,0.7686,0.001182,549.1074,-2.3699,312.8407
1,7610.0,150.80,151.80,155.43,0.1227,0.7008,0.001566,626.1527,-2.3021,287.6124
2,7620.0,143.50,144.40,147.84,0.1215,0.6863,0.001614,639.3863,-2.3161,281.9199
3,7640.0,129.10,130.00,133.07,0.1191,0.6557,0.001710,663.9164,-2.3349,269.7958
4,7680.0,102.20,103.20,105.53,0.1146,0.5875,0.001881,702.2287,-2.3335,242.4783
5,7700.0,89.90,90.90,92.86,0.1124,0.5502,0.001948,713.9764,-2.3092,227.3993
6,7720.0,78.50,79.40,81.00,0.1104,0.5110,0.002000,719.4603,-2.2669,211.5088
7,7725.0,75.70,76.60,78.12,0.1098,0.5010,0.002011,719.7472,-2.2521,207.4271
8,7730.0,73.00,73.90,75.33,0.1093,0.4909,0.002020,719.5747,-2.2371,203.3034
9,7740.0,67.80,68.70,69.96,0.1084,0.4704,0.002032,717.8100,-2.2046,194.9556
10,7750.0,62.80,63.70,64.80,0.1075,0.4497,0.002039,714.0900,-2.1667,186.4918
11,7760.0,58.10,59.00,59.94,0.1067,0.4289,0.002038,708.3827,-2.1259,177.9699
12,7770.0,53.60,54.50,55.29,0.1059,0.4081,0.002031,700.6467,-2.0798,169.3975
13,7775.0,51.40,52.30,53.02,0.1054,0.3976,0.002026,695.9943,-2.0541,165.0861
14,7780.0,49.30,50.20,50.85,0.1051,0.3871,0.002018,690.8606,-2.0285,160.7975
15,7790.0,45.20,46.10,46.62,0.1042,0.3662,0.001999,679.0205,-1.9720,152.1944
16,7820.0,34.40,35.20,35.38,0.1020,0.3048,0.001901,631.9019,-1.7806,126.8445
17,7825.0,32.90,33.70,33.83,0.1019,0.2952,0.001876,622.8261,-1.7498,122.8752
18,7850.0,25.50,26.30,26.23,0.1001,0.2470,0.001746,569.7578,-1.5634,102.9162
19,7875.0,19.70,20.20,19.98,0.0986,0.2025,0.001584,509.0952,-1.3678,84.4884
20,7900.0,14.80,15.60,15.28,0.0980,0.1646,0.001400,447.2907,-1.1879,68.7113
21,7925.0,11.20,11.80,11.43,0.0973,0.1310,0.001210,383.7496,-1.0066,54.7106
22,7950.0,8.20,8.80,8.42,0.0967,0.1023,0.001022,322.1042,-0.8357,42.7768
23,7975.0,6.00,6.60,6.22,0.0966,0.0795,0.000849,267.1343,-0.6896,33.2645
24,8050.0,2.45,2.80,2.51,0.0979,0.0361,0.000448,142.9938,-0.3701,15.1087
25,8075.0,1.85,2.20,1.94,0.0993,0.0284,0.000362,117.3133,-0.3072,11.8899
26,8100.0,1.45,1.75,1.52,0.1010,0.0225,0.000294,96.6169,-0.2565,9.4322
27,8125.0,1.15,1.45,1.24,0.1032,0.0184,0.000242,81.4494,-0.2205,7.7111
28,8400.0,0.20,0.40,0.30,0.1344,0.0040,0.000048,21.2284,-0.0735,1.6603

In [100]:
results['strike'].min(), results['strike'].max(), S

(np.float64(7540.0), np.float64(8400.0), 7711.759765625)

In [101]:
results.head(10)

,strike,market_bid,market_ask,model_price,implied_vol,delta,gamma,vega,theta_daily,rho
0,7540.0,193.9,213.7,217.87,0.1426,0.7686,0.001182,549.1074,-2.3699,312.8407
1,7610.0,150.8,151.8,155.43,0.1227,0.7008,0.001566,626.1527,-2.3021,287.6124
2,7620.0,143.5,144.4,147.84,0.1215,0.6863,0.001614,639.3863,-2.3161,281.9199
3,7640.0,129.1,130.0,133.07,0.1191,0.6557,0.001710,663.9164,-2.3349,269.7958
4,7680.0,102.2,103.2,105.53,0.1146,0.5875,0.001881,702.2287,-2.3335,242.4783
5,7700.0,89.9,90.9,92.86,0.1124,0.5502,0.001948,713.9764,-2.3092,227.3993
6,7720.0,78.5,79.4,81.00,0.1104,0.5110,0.002000,719.4603,-2.2669,211.5088
7,7725.0,75.7,76.6,78.12,0.1098,0.5010,0.002011,719.7472,-2.2521,207.4271
8,7730.0,73.0,73.9,75.33,0.1093,0.4909,0.002020,719.5747,-2.2371,203.3034
9,7740.0,67.8,68.7,69.96,0.1084,0.4704,0.002032,717.8100,-2.2046,194.9556

In [102]:
import os

os.makedirs('../data/processed', exist_ok=True)
results.to_csv('../data/processed/spx_calls_greeks_dashboard.csv', index=False)